### ISSUE TITLE
Default symbol for links messes up layout on macOS

### ISSUE THREAD

**Issue by rudolf-adamkovic** [emacs-citar/citar#321]
The link emoji makes the items with links taller, messing up the layout.

<img width="211" alt="Screen Shot 2021-10-07 at 16 21 34" src="https://user-images.githubusercontent.com/1158274/136404022-6498b2c2-7fd6-4126-a4d7-877f0206c6d6.png">

**Comment by salutis** [comment]
> But I don't think it's my bug.

That depends on how much you know and care about UIs. As you probably know, HIGs discourage the use of Unicode characters for UI elements and doubly so the characters that render as Emoji. In the situations like this, one should at least append the no-emoji modifier [1]. That said, I tried it for the link character, but that character has no textual representation. Thus, I suggest to pick a character that has textual representation, such as the arrow mentioned above. Further, I would strongly suggest appending the no-emoji modifier to all three symbols by default. Doing so will make your UI more robust, for if some OS vendor adds a pretty picture at 130 percent height in the future, it will not screw up your UI.

[1] https://mts.io/2015/04/21/unicode-symbol-render-text-emoji/
