### ISSUE TITLE
Pulling info on journal in Notes template

### ISSUE THREAD

**Issue by kbagge** [emacs-citar/citar#329]
**Describe the bug**
When trying to pull the journal title from a .bib file to the note template generated. The field is empty.
When used with the config below, date and author are pulled in correctly. 
`
;; Change the default notes template

(setq bibtex-actions-templates
      '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
        (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords:*}")
        (note . "#+title: Notes on ${title}
#+PROPERTY: authors ${author}
#+PROPERTY: journal ${journaltitle}
#+PROPERTY: date ${date}")))
`

**Expected behavior**
The note template can be filled with any information from an item in a bibtex file.

**Additional context**
I don't know if the note template is supposed to do this. So I don't know if this is a bug or a feature request. 
Thanks for your help.

**Comment by Kirbie** [comment]
Thanks for your quick replies.
I will test it tonight.

-------- Original Message --------
