### ISSUE TITLE
Add org-roam template note function

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#431]
The default org note function works well enough with org-roam. But it might be nice to have a dedicated option that uses it's template system.

I'm not very familiar with programming there, and likely don't have time to pick that up. So PR welcome.

**Comment by mbosley** [comment]
I imagine that you can pull heavily from the template structure from org-roam-bibtex?

**Comment by bdarcus** [comment]
I thought about that, but it's awfully complex.

**Comment by bdarcus** [comment]
Jethro shows a pretty simple function here:

https://jethrokuan.github.io/org-roam-guide/

**Comment by bdarcus** [comment]
Closing this; can be handled in:

https://github.com/emacs-citar/citar-org-roam
