### ISSUE TITLE
Add function to convert org-ref and/or pandoc citations to org

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#442]
Update: pandoc now supports this; just use org for input and output format.

----------

Tecosaur added a function to do this to his config. 

https://tecosaur.github.io/emacs-config/config.html#citation,code--4

Should we add something similar; maybe `citar-convert-citations` (to include pandoc) or `citar-convert-org-ref-citations` (if org-ref only)?

For those interested in this, please test out the above function and let us know if it works for you.

See also the org-ref-cite function, which relies on org-ref to handle the conversion.

https://github.com/jkitchin/org-ref-cite/blob/main/org-ref-cite-compat.el

**Comment by gkowzan** [comment]
Tecosaur's function doesn't handle citations with multiple keys, so it would be better to use pandoc.

**Comment by bdarcus** [comment]
Good point.

I'm still hopeful org-ref will support org-cite, and that it can include such a command.
