### ISSUE TITLE
Remove CRM, use CR instead

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#495]
EDIT: this needs to be resolved before 1.0, since minad removed consult-crm from consult. Vanilla `completing-read-multiple` is just not going to work.

-----------------------

Pulling this out into a separate issue ...

> ... I also wonder if some commands should just not use CRM anyway:
> `citar-insert-citation` could be modified to position point at the end of the citation, and when called again to just add new keys to the citation before point. Then you could insert multi-key citations by repeating the command, using the `embark-quit-after-action` functionality.

To me, this is the most critical command to get right, since it can either enhance the writing process, or impede it.

I'm going to focus on org, since that's my priority.

Part of the problem is that I think single vs multi citing varies quite a bit by field, and even by scholar.

Some do it all the time, and others not at all.

I personally do it less often, but still do it, and so care about getting it right.

So ideally both work really well.

The current CRM-based approach does work well with both IF you use `consult-completing-read-multiple` AND you [modify the keybindings to use TAB to select and RET to exit](https://github.com/bdarcus/citar/issues/492#issuecomment-997024450).

To ditch CRM and rely on CR only, I'm unclear how well the solution @roshanshariff suggests above would work. It may or may not be tedious.

FWIW, here's how org-ref-cite handled it (though I'm not thrilled with it)

https://github.com/jkitchin/org-ref-cite#multiple-insertions

The `oc-basic` insert processor works like this:

![image](https://user-images.githubusercontent.com/1134/146678680-16a7056c-1db3-4914-9fed-9a7418549b98.png)

... which is OK, but tends to confuse people at first ("how do I exit?").

> Similarly for `citar-open-notes` and `citar-open-entry`. You can just repeat the command if you want to open more than one.

Yes. I also think for the first `embark-act-all` is likely a better, or additional, path. I'm less concerned about the latter.

_Originally posted by @roshanshariff in https://github.com/bdarcus/citar/issues/492#issuecomment-997004886_

**Comment by jsilve24** [comment]
Did the recent changes remove the ability to select multiple citations at once when using  `citar-insert-citation`? If so, is there a way to get back the prior behavior which I had grown used to?

Thank you!

**Comment by bdarcus** [comment]
I guess it did, though wonder if that was an oversight.

Do either of you know, @roshanshariff @localauthor?

Regardless, you can set `citar-select-multiple` to `t` to get the behavior back now.

**Comment by bdarcus** [comment]
Just to update this issue, we need to figure this out, as consult-crm is now gone.

**Comment by bdarcus** [comment]
This is closed via #616.
