### ISSUE TITLE
Make file-open more configurable

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#507]
We should make opening files more configurable: use an alist as minad suggests below (though we'd maybe need to think through more what the defaults should be; particularly for pdfs):

```elisp
(defcustom citar-file-open-functions-alist
  '(("html" . #'citar-open-external) ; what about pdf?
    ("org" . #'citar-open-note)  ; do we need this here?
    (t . #'find-file))
  "Function to use to open files.

Each cons should be of the form (EXTENSION . FUNCTION)."
  :group 'citar
  :type '(alist))
```

I think this also allows us to remove `citar-file-note-extensions`.

Also, see this [related query about mailcap](https://www.mail-archive.com/emacs-orgmode@gnu.org/msg144468.html), though I didn't really understand.

I guess, beyond borrowing code, in that case they associate mime-types with open functions; so it's a different approach.

**Comment by minad** [comment]
Or make it an alist with configurable open functions for each extension? The `t` key could specify the default open function. The `t`  key as default is a common pattern in Emacs.
