### ISSUE TITLE
Support multiple notes in one org file

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#518]
## Summary

Given that org-roam has removed the file-per-note restriction (see also #517), we might do the same.

## Details

I'm just not sure how best to do that ATM, as I don't have a ton of experience coding and working with org structure.

There are also, I think, some design nuances to consider; for example:

If we remove this restriction, seems it should be more flexible than only a single org file. For example, maybe I want to mix single-per-file and multi-per-file (though not sure that's a great idea in org-roam given its robust linking, along with [transclusion](https://github.com/nobiot/org-transclusion))? 

Regardless, how to best configure what UX here?

OTOH, maybe if people want that sort of flexibility, they should store the note file paths in the actual record?

## Counterpoint

One could reasonably argue this is not worth the hassle, and that we have a design now that works well for one-file-per-note/reference use cases, that this is increasingly what we're seeing in diverse new note-taking packages, and that users here aren't actually requesting it. For that reason, I've marked the milestone as "future" (post 1.0).

**Comment by ademberbic** [comment]
Hi @bdarcus, thank you so much for your work on this package, it's been a joy to use so far! For whatever it's worth, I recently slapped together a few functions to add this functionality to citar à la ivy-bibtex, which I'd been using before. Needless to say that it's very quick-and-dirty code, and you may well have had a completely different implementation in mind, but [here it is](https://gist.github.com/ademberbic/f99a15dc4a38d1dedd3235b26ae6828c) nonetheless. Hope it proves useful, and thanks again.

**Comment by bdarcus** [comment]
Thanks @ademberbic. Based on this, do you have any inputs on my design questions above?

I don't actually recall how ivy-bibtex handles this.

**Comment by ademberbic** [comment]
Good question @bdarcus—I'm not at all familiar with org-roam myself, so I'm afraid I can only be of so much use here.

With ivy-bibtex and helm/bibtex, it's an either/or choice: if `bibtex-completion-notes-path` is a filename, it assumes one-file-for-notes; if it's a directory, it assumes one-file-per-note. Their implementation is [here](https://github.com/tmalsburg/helm-bibtex/blob/ce8c17690ddad73d01531084b282f221f8eb6669/bibtex-completion.el#L1398): if multiple keys are selected (which, out of laziness, my code assumes will never happen), it either opens all the notes files or opens an org-capture-style narrowed buffer for each, depending on the system in use.

In terms of mixing one-file-for-notes and one-note-per-file, I suppose I could imagine a setup where `citar-notes-paths` takes filenames for the former as well as directories for the latter: existing notes are found by scanning everything in the list for org properties holding the BibTeX key, as in ivy-bibtex; new notes are added to the first entry in the list, be it a file or a directory. But that's a pretty cludgy, convoluted set-up (e.g. what if a user wants to choose how and where a new note is stored?), and I have no idea how well it would play with org-roam.

Maybe you're right that, if a user wants that much flexibility, they should store the note path in the record itself. I can imagine situations where it'd be useful (e.g. a 'master' notes directory, and then files that collect notes on everything I'm reading for a given project)—but I can equally imagine it all getting very messy, very quick. I think this one's your call.

**Comment by bdarcus** [comment]
> Good question @bdarcus—I'm not at all familiar with org-roam myself, so I'm afraid I can only be of so much use here.

Just to clarify, I use the org-roam example just because it's the most widely used package for this, and I use it.

But it's really a general question.
 
> With ivy-bibtex and helm-bibtex, it's an either/or choice: if `bibtex-completion-notes-path` is a filename, it assumes one-file-for-notes; if it's a directory, it assumes one-file-per-note. 

Right; that's what I was assuming. And you then can't specify more than one file?

> Their implementation is [here](https://github.com/tmalsburg/helm-bibtex/blob/ce8c17690ddad73d01531084b282f221f8eb6669/bibtex-completion.el#L1398): if multiple keys are selected (which, out of laziness, my code assumes will never happen), it either opens all the notes files or opens an org-capture-style narrowed buffer for each, depending on the system in use.

So it could open the same file in multiple buffers then?
 
> In terms of mixing one-file-for-notes and one-note-per-file, I suppose I could imagine a setup where `citar-notes-paths` takes filenames for the former as well as directories for the latter: existing notes are found by scanning everything in the list for org properties holding the BibTeX key, as in ivy-bibtex; new notes are added to the first entry in the list, be it a file or a directory. But that's a pretty cludgy, convoluted set-up (e.g. what if a user wants to choose how and where a new note is stored?), and I have no idea how well it would play with org-roam.

I would also worry about the performance implications of that.

**Comment by ademberbic** [comment]
> Right; that's what I was assuming. And you then can't specify more than one file?

Correct, the variable `bibtex-completion-notes-path` expects a string, and refuses to accept lists.

> So it could open the same file in multiple buffers then?

In theory, yes, but I've just given it a try and it looks like their implementation is buggy. It spawns an org-capture-style window to edit notes, but if you pass multiple keys to `bibtex-completion-edit-notes`, it'll loop over them and keep re-expanding and re-narrowing the notes file until you're left looking at the final key you requested.

I imagine you could implement this properly with indirect buffers, each narrowed to the relevant subheading—I think that's how org-capture itself does it—but if each key the user selected spawns its own window, there's the question of how to lay them all out.

**Comment by bdarcus** [comment]
> Maybe a solution would be providing a citar-find-resources-function or something along these lines, that would allow us to find custom resources for a citekey?

That would likely make sense, as a generalization of the functions we use now to find related files.

As is occurs to me now, it might be worth mentioning that if we're concerned about performance here, maybe it's time to consider a SQLite solution, as org-roam does? Emacs now has out-of-box support for SQLite, presumably for just this sort of situation.

**Comment by bdarcus** [comment]
> Hey @bdarcus, thanks a lot for citar. I'm chiming in with my use-case, maybe this will help shaping up this functionality:

Hi @alarsyo!  

To be clear, I totally get the sort of use cases, and have no objection in principle.

To me it's just a question of how to do it elegantly, that fits well with the existing design.

And since I myself haven't seen a need for it, I don't have a huge incentive to figure it out and code it.

Which is to say, happy to accept PRs ;-)

**Comment by bdarcus** [comment]
> Which makes me also wonder about something more tightly coupled to OR (v2); say a citar-org-roam.

@jethrokuan - any thoughts or tips on this?

**Comment by bdarcus** [comment]
I've decided to close this issue, and instead make citar a bit more configurable. See the linked issues.

**Comment by bdarcus** [comment]
For the adventurous, if you want to test this, I think it should be ready (though don't be surprised if there are some hiccups).

https://github.com/bdarcus/citar/pull/609

**Comment by bdarcus** [comment]
No huge rush; it will probably take a week or so before I've fixed some things I know need fixing.

**Comment by bdarcus** [comment]
Closing this again; this will be handled in https://github.com/emacs-citar/citar-org-roam.
