### ISSUE TITLE
toggle completing-read-multiple with a prefix arg?

### ISSUE THREAD

**Issue by titaniumbones** [emacs-citar/citar#558]
I wonder if it would be useful to allow users to temporarily reverse the value of `citar-select-multiple`. I know that I personally mostly insert single citations, but about a quarter of the time I want to cite multiple sources.  `C-u C-c b` would be (for me at least) a convenient way to temporarily allow multiple selection. 

Another option I guess would be to just write my own trivial function that just calls `org-cite-insert` after let-binding `citar-select-multiple` to its negation, and bind that to say `C-c B`; but this feels more opaque and brittle than a built-in solution.  

What do you think?

**Comment by bdarcus** [comment]
I think it's definitely a good question. As I mentioned in https://github.com/bdarcus/citar/issues/495#issuecomment-1041883680, the default to CR was probably a mistake.

I'm not sure ATM how best to proceed, as this variable currently impacts all commands, while toggling is likely most useful for only one or two.

**Comment by bdarcus** [comment]
Any input on this @roshanshariff? I'm a little confused by the code, and how to proceed.

The suggestion here does seem sensible to me though.

**Comment by localauthor** [comment]
I haven't really delved into using styles in org-cite, and I don't immediately see an elegant way of handling this proposal, given that prefix-arg is already spoken for by org-cite. But I'll keep thinking on it.

 In the meantime, as I'm trying out the prefix-argument routine, I'm running into a discrepancy in the behaviors of `org-cite-insert` and `citar-insert-citation` in org-mode , ie, `citar-org-insert-citation`.

When I call `org-cite-insert` with a prefix-arg then select a style, I get the following (for example):
[cite/text/cf:@Author2000]

When I call `citar-insert-citation` with a prefix-arg, I'm not prompted to select a style, and I simply get this:
[cite(4):@Author2000]

Can you replicate this, or am I missing something?

**Comment by bdarcus** [comment]
It's not surprising that `citar-insert-citation` doesn't behave the same way, as the logic for `org-cite-insert` is contained in `org-cite-make-insert-processor`.

But are you saying the output is wrong? If yes, I'll have to test that.

**Comment by localauthor** [comment]
> It's not surprising that `citar-insert-citation` doesn't behave the same way, as the logic for `org-cite-insert` is contained in `org-cite-make-insert-processor`.

Seems to me that they should behave the same way, to avoid any surprises to the user.

> But are you saying the output is wrong? If yes, I'll have to test that.

Yes, the '4' is just the value of the prefix-argument. So the style argument of `citar-org-insert-citation` isn't being translated into a style.

Adding something like the following conditional to `citar-org-insert-citation` (after the initial let statement) would seem to suffice, but again maybe I'm missing something:

`(when style (setq style (concat "/" (citar-org-select-style))))`

> The more I think about it, the more I think the insert citation functions should just use CRM.

I can't remember why exactly the original objection to CRM arose, although I don't really use it myself. It seems that having the variable `citar-select-multiple` is a good way of leaving possibilities open, no matter what the default setting is.

**Comment by bdarcus** [comment]
I think I fixed it in the latest commit.

**Comment by bdarcus** [comment]
I think with #616 this is unlikely to be necessary.
