### ISSUE TITLE
Status of completing-read-multiple, consult-crm in citar?

### ISSUE THREAD

**Issue by minad** [emacs-citar/citar#582]
Hello @bdarcus,

I wanted to ask about the current status of CRM in Citar? You switched to CR by default right? Unfortunately it turned out that consult-crm is too simplistic. Since I am in the process of stabilizing my packages for 1.0, features which are fundamentally broken have to be removed. I am not happy with removing this but I don't really see how we can salvage the current implementation. See https://github.com/minad/consult/issues/567 for details. Maybe we will get a new implementation but in principle this puts us back at square one regarding how the CRM UI should look :(

**Comment by bdarcus** [comment]
Hi @minad - I was just thinking about that today. Thanks for asking.

The issue to document/track this question is mostly #495.

To boil it down, however, for almost all commands, it's not a problem to ditch crm.

The sole exception is a very important command: `citar-insert-citation` (and `org-cite-insert` when using citar as the insert processor).

I'm still not sure what a good solution there is.

If removing multiple selection itself is not ideal, I suppose a Plan B is to do a citar implementation of your code, as you originally proposed in #160?

Any other ideas?

PS - one wildcard ATM, that I have not had time to explore more fully, is embark multiple support. But I think that's less critical than the above.

**Comment by minad** [comment]
Yes, you could add back a simple implementation in citar which calls Cr in a loop. Maybe we will see a new implementation since @Hugo-Heagren mentioned that he may be interested in this.

**Comment by minad** [comment]
See also https://github.com/DarwinAwardWinner/crm-custom.

**Comment by bdarcus** [comment]
> Yes, you could add back a simple implementation in citar which calls Cr in a loop. Maybe we will see a new implementation since @Hugo-Heagren mentioned that he may be interested in this.

Cool; he's actually contributed to this project!

The second one is marked "experimental", which doesn't sound very encouraging.

**Comment by minad** [comment]
I am not saying that one should use custom-crm, but it uses essentially a similar idea as consult-crm.

**Comment by bdarcus** [comment]
Does it have the same limitations as consult-crm?

**Comment by minad** [comment]
I don't know.

**Comment by bdarcus** [comment]
@iyefrat - you might be interested in this for the doom vertico module; consult-crm is now effectively gone.

https://github.com/minad/consult/commit/8e9d5e73582a38c1c48d5d392c42870aac1e9abf

**Comment by aikrahguzar** [comment]
`crm` provided a really nice ui for `citar-insert-citation` so this is a bit sad. Though I think the ui can probably be recreated using only `completing-read` provided there is a way of accessing the currently selected candidate during a search.

As a sketch I think:
  1) Use a variable `citar--selection` to hold the list of selected candidates, it is set to nil at the start of every search.  
  2) Create a group function which checks membership in this list. (I don't know if grouping which change during the search work or are a good idea, keeping the group of selected items on top might be another issue).
  3) Toggling the selection then add or removes the element from `citar--selection` as needed. 
  4) When the search is done we add the returned element to it and do what we need. 

But we need to know the currently selected candidate to add or remove it from the list and I don't know if there is a generally accepted way of doing it. The closest I know of is `consult--completion-candidate-hook` and looking at the elements in it, it seems this is dependent on the completion ui. Maybe there is another solution for this problem in embark?

**Comment by bdarcus** [comment]
> `crm` provided a really nice ui for `citar-insert-citation` so this is a bit sad.

Yeah. With the right keybindings, a la vertico-crm, it's pretty much ideal for this use case.

**Comment by minad** [comment]
In principle you can import consult-crm to citar as is and call it directly there, since for the use case of citar it should work well. It is just not a general solution and as such is misplaced in Consult, where I tried to offer this as replacement for the builtin default completing-read.

**Comment by bdarcus** [comment]
By "import" you mean in essence fork that function and add it here @minad? Not that any of that code remains in consult?

**Comment by minad** [comment]
Yes. But it won't work since it uses some Consult features. But you could achieve almost the same by calling Cr in a loop.

**Comment by minad** [comment]
You should probably update the readme too - remove mentioning of consult-crm. You can still recommend consult independently if you like.

(Unrelated, but maybe drop the recommendation of Selectrum? It is not yet clear how long this will take, but Selectrum is probably going to sunset.)

**Comment by bdarcus** [comment]
> You should probably update the readme too - remove mentioning of consult-crm. You can still recommend consult independently if you like.

Yes; thanks for the reminder; been meaning to do that!
 
> (Unrelated, but maybe drop the recommendation of Selectrum? It is not yet clear how long this will take, but Selectrum is probably going to sunset.)

Been meaning to do that too!

**Comment by bdarcus** [comment]
Done.
