### ISSUE TITLE
Suffix appended without whitespace

### ISSUE THREAD

**Issue by denismaier** [emacs-citar/citar#606]
1. Enter a citation
2. Run `citar-org-update-pre-suffix`
3. Enter a suffix.

=> the suffix is inserted without any separating whitespace. Is this the intended behaviour?

**Comment by bdarcus** [comment]
I vaguely recall this is something about org-cite. I'll see if I can find the email.

**Comment by bdarcus** [comment]
Here's my email to the list, and the subsequent thread.

https://lists.gnu.org/archive/html/emacs-orgmode/2021-10/msg00472.html

**Comment by bdarcus** [comment]
OIC; yes, that's an obvious bug. I never use that function, so never came across it!

**Comment by bdarcus** [comment]
So what's should the behavior be, do you think?

Add a space after the prefix and before the suffix?

**Comment by denismaier** [comment]
> Add a space after the prefix and before the suffix?

I'd think so, yes.

**Comment by bdarcus** [comment]
Only thing is, if one is updating an existing affix, one wouldn't want to add the spaces.

**Comment by denismaier** [comment]
Ok, looks like this is really caused by `org-element-interpret-data`

```
(org-element-interpret-data `(citation-reference (:key "asdf" :prefix "prefix" :suffix "suffix")))

; vs:

(org-element-interpret-data `(citation-reference (:key "asdf" :prefix "prefix " :suffix " suffix")))
```

**Comment by bdarcus** [comment]
Yeah; I kind of think that's a bug in org. WDYT?

**Comment by denismaier** [comment]
Probably yes. I can't claim to totally understand what is happening there, though.
