### ISSUE TITLE
run `org-cite-insert` in a org-mode buffer, then popup error `Unknown processor citar`

### ISSUE THREAD

**Issue by nicehiro** [emacs-citar/citar#615]
**Describe the bug**
run `org-cite-insert` in a org-mode buffer, then popup error `Unknown processor citar`

**To Reproduce**
My org-cite config:
```
(setq org-cite-global-bibliography hiro/bib-libraries
      org-cite-insert-processor 'citar
      org-cite-follow-processor 'citar
      org-cite-activate-processor 'citar
      org-cite-export-processors '((latex biblatex)
                                   (t csl)))
```
Just run `org-cite-insert` in a org file buffer

**Expected behavior**
insert citation in an org buffer

**Emacs version:**
29.0.50

**Additional context**
org version: 9.5.3

**Comment by bdarcus** [comment]
Have you had any luck with this, or come across any more info?

This shouldn't happen, so am not sure what it could be.

**Comment by bdarcus** [comment]
Also, if not, what happens if you first run a citar-specific command, and then `org-cite-insert`?

**Comment by nicehiro** [comment]
> come across any more info

There's no more info. I've already `toggle-debug-on-error`.


> Also, if not, what happens if you first run a citar-specific command, and then `org-cite-insert`?

Other citar-specific command works fine, like `citar-open`. Same thing happened when I call `org-cite-insert` after run `citar-open`.

**Comment by bdarcus** [comment]
Where are those `setq` statements in the config? Maybe a load order issue?

For context, about six months ago we were having this sort of problem. But since then, we autoload the processor, and haven't seen that bug since.

https://github.com/emacs-citar/citar/blob/c32623df2d90e987edaa8a90b53d137c103f7eb1/citar-org.el#L462-L465

**Comment by nicehiro** [comment]
I checked the `org-cite--processors` and didn't find `citar` in here. 

I use `git submodules` to manage packages, it seems that my config cannot auto create `xxx-autoload.el` files and load them.

Anyway, the problem solved when I require `citar-org` by hand.

Thanks for you time. I'll find someway to better config `autoload` files.

**Comment by bdarcus** [comment]
Sounds good.

Note that a lot of functionality here depends on autoload; notably the major mode functions in general.
