### ISSUE TITLE
Broken history?

### ISSUE THREAD

**Issue by salutis** [emacs-citar/citar#620]
I updated Citar (but also million other things, including Emacs from Git), and `citar-history` stopped working (just for Citar).  For instance, I currently study a book on biology, citing from it (for my notes) every day.  Yet, the book does not come first in `citar-open` and comes last (???) in `org-cite-insert` when I type `biology`.  Citar does not have a test suite, so I decided to ask here first (because we should expect regressions).  Anyone sees the problem, or should I investigate my setup?  Thanks!

**Comment by salutis** [comment]
Oops!  I restarted Emacs and `citar-open` now has the biology book first.  Still, the `org-cite-insert` has it last (after I search for `biology`).  Has anything changed there?

**Comment by bdarcus** [comment]
Yes; big change for multiple selection.

https://github.com/emacs-citar/citar/commit/ddc08dedd40da3af79bcbc51ba71dfbdc39a7888

I'll take a look, but cc @aikrahguzar.

**Comment by aikrahguzar** [comment]
Should be fixed by #622 
This is due to setting `display-sort-function` in metadata which means vertico doesn't use its own sort function.

**Comment by aikrahguzar** [comment]
> > Oops!  I restarted Emacs, and `citar-open` now has the biology book first.  Still, `org-cite-insert` lists it last (after I search for `biology`).  Has anything changed there?
> 
> FYI: This behaves strangely. If I start Emacs and call `citar-open`, I see the biology book first. All good. Then, if I start Emacs, maximize its window, and then call `citar-open`, I see some other item first. I repeated the experiment 5 times, every time getting the same results. What in the world!

Is this with the latest commit?

**Comment by salutis** [comment]
> Is this with the latest commit?

Nope.

**Comment by salutis** [comment]
The update has arrived, and it fixes all the problems described above.  Thank you!
