### ISSUE TITLE
Revise note API (again)

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#646]
We need to revise again the note API so that notes work correctly with `citar-open`, while also being configurable, but I suggest we do this after #634.

-------

## The problem

With notes, the issue is that we don't can't assume the category is always a file; it could also be some sub-file section. 

For purposes of this discussion, the completion category can be `file` or `org-roam-node`.

If the category is `file`, then the candidates need be no different than `citar-get-files`; it's only with the `org-roam-node` case that it gets complicated. 

And even more specifically, it's only if we insist on allowing different categories within the same group, which I'm skeptical about. I'm not even clear how we do that from a technical POV.

## Proposed solution

Per minad [below](https://github.com/emacs-citar/citar/issues/646#issuecomment-1172355905):

> ... use the multi-category category in the same way as consult--multi uses it. The multi-category is also supported by Marginalia and Embark. The candidates must carry a multi-category text property, see consult--multi-candidates.

So have `citar-get-notes` return a list of completion strings regardless of completion category, and change `citar-open-note-functions` to a plist something like this, which is how `consult--multi` does it:

```elisp
(defvar citar-org-roam-open-notes-config
  `(:name "Org-Roam Ref Notes"
    :category 'org-roam-node
    :key-predicate ,#'citar-org-roam-has-note
    :action ,#'citar-org-roam-open-note-from-id
    :items ,#'citar-org-roam--get-candidates))
```

That's simple and flexible, with the sole constraint that all notes within a group must be the same category.

Then with citar-org-roam can just do:

```elisp
(setq citar-notes-config citar-org-roam-open-notes-config) ; the package can include the plist for easy config
```

On the candidates: I have an experimental `citar-org-roam--get-ref-nodes` function in the citar-org-roam repo that returns a list of propertized strings, using the hidden id trick, with citekey and title in the visible part.

![image](https://user-images.githubusercontent.com/1134/176499581-b10bae9b-b640-4f96-bef5-3584e19196cd.png)

## Conclusion

I see no downside to this approach. I think the question is just whether the defcustom becomes `citar-notes-config`, or `citar-notes-configs`. The latter would allow multiple plists, and hence notes groups. I have no opinion on this question.

Except, if it's a list, the whole `citar-open` UI may as well be configured with this approach; not just notes? So `citar-open-config`?

```elisp
(setq citar-open-config '(citar-open-note-config citar-open-file-config citar-open-link-config))
```

_Originally posted by @bdarcus in https://github.com/emacs-citar/citar/pull/634#issuecomment-1169836613_

**Comment by minad** [comment]
This doesn't look like a good use case of consult--multi. consult--multi is mostly useful if the sources can be configured flexibly and if they are not hard coded. If you have hard coded sources anyway I suggest to use completing-read with the group-function.

**Comment by bdarcus** [comment]
> I suggest to use completing-read with the group-function.

That's what we do now.

Any tips how to address the fact that we have multiple categories, and in the case of notes, we won't know what they are upfront (can be files, as now, or with Org-Roam can be files or sub-file nodes)?

I don't really understand that part of `completing-read`, though perhaps @roshanshariff does.

**Comment by bdarcus** [comment]
> You should read through the Consult source for the details.

Yes, I have. I just wanted to confirm that.

As always, thank you!

So no to `consult--multi`, but yes to `multi-category` and to `consult--multi`-like source config plists.

**Comment by bdarcus** [comment]
I have an idea for a possible solution:

Add an optional `note-nodes` arg to `citar--select-resource`.

Actually, have all the args optional then, and have them keywords?

**Comment by bdarcus** [comment]
Looking now at note config, here's the new plist as it stands:

```elisp
(defvar citar-notes-config-file
  `(:name "Notes"
    :category file
    :key-predicate ,#'citar-file-has-notes
    :action ,#'citar-file--open-note
    :items ,#'citar--get-file-notes)
  "Default file-per-note configuration.")
```

And here's the current defcustoms:

1. `citar-create-note-function`
2. `citar-has-notes-functions`
3. `citar-open-note-function`
4. `citar-open-note-functions`

Observations/thoughts:

- Obviously the last two are redundant, and all of them need to be deprecated.
- As I said above, I don't think we need multiple open functions here. If we need that flexibility, we can perhaps expand to allow multiple plists, where there could be multiple notes groups.
- I think the single `:action` function is enough for opening and creating, but am not sure. Probably need to check how ORB would fit here.
- If it's not, we can always add another property for this to distinguish `:open` and `:create`.

**Comment by bdarcus** [comment]
@myshevchuk - turns out our [earlier discussion](https://github.com/org-roam/org-roam-bibtex/issues/244) on note config got a little more complex. Any feedback, particularly on my [last post](https://github.com/emacs-citar/citar/issues/646#issuecomment-1172937293)?

These changes will allow a package like ORB to directly update the citar UI for presence of notes, configure the candidate display (including annotations), and open the selected candidate from `citar-open` or `citar-open-notes`.

The idea would be to keep the current defcustom around a bit, until I tag v1.0 sometime in the next month or so.

**Comment by roshanshariff** [comment]
@bdarcus, I like the new API design. I would just make one small change: instead of just having the `citar-notes-config` variable be a plist, it should be an alist (maybe called `citar-notes-sources`). The keys should be the names of notes backends, and the values should be plists. Something like
```elisp
(defcustom citar-notes-sources ((citar-file . PLIST))
```

Then there should be another variable which selects the source (or sources) to actually use, which will actually be modified by the user:
```elisp
(defcustom citar-notes-source 'citar-org-file)
```

Then `citar-org-roam` can add itself to `citar-notes-sources` when it's loaded, but there won't be any change in behaviour until the user changes `citar-notes-source`. This is a common pattern in other libraries (e.g. `org-export-registered-backends`)

**Comment by bdarcus** [comment]
@roshanshariff OK, will take a look tomorrow.

While I have you, do you know how to modify our group function so it will work with non-file notes? This is the primary bug I'm stuck on.

Can we just inspect the `multi-category` metadata?

```elisp
(defun citar--select-group-related-resources (resource transform)
  "Group RESOURCE by type or TRANSFORM."
  (let ((extension (file-name-extension resource)))
    (if transform
        (if (file-regular-p resource)
            (file-name-nondirectory resource)
          resource)
      (cond
       ;; FIX doesn't work with node-id notes
       ((member extension citar-file-note-extensions) "Notes")
       ((string-prefix-p "http" resource 'ignore-case) "Links")
       (t "Library Files")))))
```

**Comment by roshanshariff** [comment]
Maybe `citar--select-resource` could add its own text property to the candidates? Maybe something like `'citar--resource-type` which can be `'file`, `'note`, or `'link`. Then `citar--select-group-related-resources` would just read that property and return the group name.

**Comment by bdarcus** [comment]
I was thinking it's valuable to use `'file` as category for file notes, given annotations, embark, etc.

So distinguish file notes from node-notes.

**Comment by roshanshariff** [comment]
Maybe the `'multi-category` property annotation can be left to the note backend providers? That way. for example, `citar-org-roam` could apply the `file` category to Org IDs that map to files, but not to those that map to nodes within a file. Then `citar--select-resource` would just use the candidates it got from the back-end as-is (just adding its own property for the grouping function to use).

**Comment by bdarcus** [comment]
Right now, the category is specified in the plist, so I think it's already as you suggest.

**Comment by bdarcus** [comment]
Maybe we could define default category as `'note-file` and use the marginalia annotation for that?

**Comment by bdarcus** [comment]
I pushed the defcustoms, but can't figure out how to access the plists.

```elisp
ELISP> (plist-get (cdr (assoc 'citar-file citar-notes-sources)) :name)
nil
```

And here's what I have:

```elisp
(defcustom citar-notes-sources
  '((citar-file . citar-notes-config-file))
```

**Comment by bdarcus** [comment]
> Maybe `citar--select-resource` could add its own text property to the candidates?

I ended up add a `notep` property to note candidates, and then the group function uses that, or falls back to the completion category, which are fixed for files and links:

```elisp
      (if notep (plist-get citar-notes-config :name)
        (pcase cat
          ('file "Library Files")
          ('url "Links"))))))
```

**Comment by bdarcus** [comment]
> I pushed the defcustoms, but can't figure out how to access the plists from them.

I implemented it with some help from someone suggesting:

> A better approach is to initialize t/config like this
> (defcustom t/config `((test1 . ,(list :one 1 :two 2))))
>
> Then a user can modify (cdr (assq 'test1 t/config)) directly using setf or alike

**Comment by myshevchuk** [comment]
> @myshevchuk - turns out our [earlier discussion](https://github.com/org-roam/org-roam-bibtex/issues/244) on note config got a little more complex. Any feedback, particularly on my [last post](https://github.com/emacs-citar/citar/issues/646#issuecomment-1172937293)?
> 
> These changes will allow a package like ORB to directly update the citar UI for presence of notes, configure the candidate display (including annotations), and open the selected candidate from `citar-open` or `citar-open-notes`.
> 
> The idea would be to keep the current defcustom around a bit, until I tag v1.0 sometime in the next month or so.
> 
> Or I suppose we could iterate the current config approach.

I definitely love the approach where an external package like ORB could feed the necessary information to Citar using the exposed API. I remember the difficulties I had with ORB trying to hijack Ivy-bibtex to update the "has-note" indicator, and I think it ended up buggy anyway.

I can't speak much about the new Citar API right now because I haven't had time to look at it in detail yet. In any case, the suggested fine-grained control over the different citation resources looks very thorough and systematic. Whatever the new Citar API will look like, ORB will support it.

**Comment by bdarcus** [comment]
@myshevchuk - sounds good.

Note I'm developing this small extension alongside this to make sure the API is correct.

https://github.com/emacs-citar/citar-org-roam/blob/main/citar-org-roam.el

I'm not sure how it will evolve, but am thinking it will remain pretty small and just handle the integration, and other packages can  build on it. Or they write their own integration functions, and that becomes a demonstration of how.

**Comment by bdarcus** [comment]
Here's another example of a notes source, using the new API; from today!

https://github.com/localauthor/zk/blob/main/zk-citar.el

**Comment by bdarcus** [comment]
@myshevchuk 

> Whatever the new Citar API will look like, ORB will support it.

FYI, I'll be tagging 1.0 in the coming days, and then bumping the doom biblio module.

I will post this on the wiki, I think, for folks who want to continue to use ORB:

```elisp
(defconst orb-citar-source
  (list :name "Org-Roam Notes"
        :category 'org-roam-node
        :items #'citar-org-roam--get-candidates
        :hasitems #'citar-org-roam-has-notes
        :open #'citar-org-roam-open-note
        :create #'orb-citar-edit-note
        :annotate #'citar-org-roam--annotate))
        
(citar-register-notes-source
 'orb-citar-source)

(setq citar-notes-source 'orb-citar-source)
```

**Comment by myshevchuk** [comment]
@bdarcus excellent! I will update the ORB readme too.

**Comment by bdarcus** [comment]
We should probably note that this requires https://github.com/emacs-citar/citar-org-roam.

**Comment by cdlm** [comment]
FYI seems like `citar-register-notes-source` wants two arguments now (and while debugging that last night, I didn't understand the need for `defconst`?)

**Comment by bdarcus** [comment]
It's always had two arguments, since it's just adding to an alist.

I wasn't sure on your second question either; @roshanshariff?

**Comment by roshanshariff** [comment]
I'm not sure I understand, but there's never any "need" for `defconst`. You can always just use a `defvar` instead if you prefer. Or even skip giving the plist a name:
```elisp
(citar-register-notes-source 'my-notes-source '(:name "My Notes Source" :create my-note-create-function ...))
```

But in `citar-org-roam`, the `citar-org-roam-config` plist constitutes some metadata about the package itself (specifically, the functions it exposes to manipulate notes) so it's semantically a constant. There shouldn't be any need to modify it unless you're changing the package.

The `defconst` also reminds you that changing the variable won't affect the actual notes source in `citar` unless you again run `citar-register-notes-source`. But if you find yourself wanting to change it, you're probably better of making your own notes source by copying and modifying. For example, to make your own source that is like the Org-Roam one but with a different create function:
```elisp
(citar-register-notes-source 'my-notes-source (plist-put (copy-sequence citar-org-roam-config) :create #'my-note-create-function)
(setq citar-notes-source 'my-notes-source)
```

I hope that answers your question, but I'm happy to clarify otherwise.
