### ISSUE TITLE
Citar now seems to require Embark

### ISSUE THREAD

**Issue by bertulli** [emacs-citar/citar#648]
Hi,
upon updating my Emacs packages (`M-x package-list-packages` > `U` > `x` > `y`), I got the following error
```
Compiling file /home/alessandro/.emacs.d/elpa/citar-20220704.2120/citar-embark.el at Tue Jul  5 15:27:19 2022
citar-embark.el:23:1: Error: Cannot open load file: No such file or directory, embark
```
Indeed, following the link, I can see the file `citar-embark.el` has a line `(require 'embark)` (line 23), but the package doesn't require it, so it's not automatically installed. I don't know if this blocks the loading of the package, but I thought it was worth mentioning (or, if the bug is harmless, maybe put a warning in a FAQ?)

My Emacs version is `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-28`. Note also that I don't use external package managers (like `use-package` or `straight`).

**Comment by bdarcus** [comment]
In the major commit I just merged yesterday, we split off a separate `citar-embark` package and minor mode.

I submitted a PR to MELPA just after that; hopefully it'll be merged today.

https://github.com/melpa/melpa/pull/8108

The `citar-embark.el` file indeed requires embark.

https://github.com/emacs-citar/citar/blob/5f22f2711205ebd62d68979f2885524515fe0dba/citar-embark.el#L13

Sorry for the (temporary) hassle.

**Comment by bdarcus** [comment]
Did you figure this out @bertulli?

**Comment by bertulli** [comment]
Sorry for the delay!
Right now, `citar` still tries to include `citar-embark`, even if I delete and reinstall it (like I didn't see it as a separate package).
I am not familiar with manually excluding files: do you mean delete the `citar-embark.el` file from the citar directory (`citar-20220705.2057`)? Or is there something I need to set (like an `EXTRA_PROPERTY`) in `citar-pkg.el`?

**Comment by bdarcus** [comment]
I don't actually know. Where is a `citar-pkg.el` file?

@roshanshariff this may be a hassle of keeping citar-embark in this repo.

**Comment by bdarcus** [comment]
Actually, if you use package install, it should just use the MELPA recipe. So once they merge the changes, it should be fine.

**Comment by bertulli** [comment]
Thanks, I'll wait for it then. Anyway, in my `.emacs.d/elpa/citar-20220705.2057` directory I see a file called `citar-pkg.el`, with the following content:
``` emacs-lisp
(define-package "citar" "20220705.2057" "Citation-related commands for org, latex, markdown"
  '((emacs "27.1")
    (parsebib "3.0")
    (org "9.5")
    (citeproc "0.9"))
  :commit "6b21e226a4d37c64b7d78c47b018303eeb6b25c0" :authors
  '(("Bruce D'Arcus <https://github.com/bdarcus>"))
  :maintainer
  '("Bruce D'Arcus <https://github.com/bdarcus>")
  :url "https://github.com/bdarcus/citar")
;; Local Variables:
;; no-byte-compile: t
;; End:
```

**Comment by bdarcus** [comment]
MELPA recipes just updated.

May take a few hours to build etc, but please confirm, and close this if OK?

**Comment by bertulli** [comment]
Well, manually reinstalling `citar` now doesn't raise errors, and now I see a new package `citar-embark`, so I'll close the issue. Thank you for your patience and your kindness!
