### ISSUE TITLE
Refactor `citar-capf`

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#660]
I think `citar-capf` is going to need some more extensive changes. Currently it just saves the active bibliographies whenever `citar-capf` is loaded and then never updates them. But we also can't update it every time `capf` is called. We'll need to do something a little more involved so it's reasonably fast but also updates when the bibliiographies change (and respects the buffer's local bibliographies).

_Originally posted by @roshanshariff in https://github.com/emacs-citar/citar/issues/653#issuecomment-1186612775_

**Comment by bdarcus** [comment]
I forgot to cc you on this @mclearc; just FYI, in case you missed it, or were wondering.

**Comment by bdarcus** [comment]
Just coming back to this, it seems like it would still be useful without the "extensive changes," so perhaps the first step is just to add it to the README, with the caveat?

**Comment by bdarcus** [comment]
So the problem is  `citar-capf--candidates `.

Maybe this is a dumb question, as I haven't been thinking about this for awhile, but ...

Do we even need a separate cache for the capf? Could we not just use the main citar one; what citar itself uses?

@roshanshariff

**Comment by roshanshariff** [comment]
Citar does have a cache that it keeps updated as bib files change, but this is not per-buffer. When you run a command, it scans the file to find active bibliographies, collects together their entries from the cache, and formats them to fit the screen. This only takes a fraction of a second and uses some amount of memory for the freshly-created hash table to hold everything, which is fine for most citar commands.

I think the justification for the capf cache is to avoid this for (potentially) every keystroke; some people have completion pop-up after every key, or after a small delay. Also, the citar cache will update whenever a bib file changes, which can take a few seconds. It might be okay to deal with this when you call a citar command, but it would probably get annoying if it kept happening as you were typing. And creating a new hash table every time would probably cause frequent garbage collection slowdowns.

**Comment by bdarcus** [comment]
@roshanshariff - what about just accessing the preformatted strings for the capf, since the other stuff isn't needed in this context? 

E.g.:

```elisp
(citar-cache--preformatted (citar--bibliographies) ; if the inner function can account for local bibs
```

**Comment by bdarcus** [comment]
I merged the linked PR, which I think at least is an improvement. But I probably missed some detail.
