### ISSUE TITLE
can not generate local-bib after escape symbols

### ISSUE THREAD

**Issue by hy-zhao** [emacs-citar/citar#662]
**Describe the bug**
when I cite after an escaping symbol, the following citation item can not be exported to local-bib file.

**To Reproduce**
1. `\%\cite{gaoEfficientKnowledgeGraph2019}`
2. `citar-export-local-bib-file`

**Expected behavior**
Referece item related to `gaoEfficientKnowledgeGraph2019` should be exported. But it doesn't. If i make `\cite{gaoEfficientKnowledgeGraph2019}` to a new line, the export will work. Is it impossible to solve this bug?

**Emacs version: 28**

**Comment by bdarcus** [comment]
Any thoughts @aikrahguzar?

**Comment by aikrahguzar** [comment]
As far as I can tell, for latex  `citar-export-local-bib-file` gets keys from `reftex-all-used-citation-keys`. So my guess is reftex ignores comment but isn't smart about determining what is a comment. I don't think we should try to fix this in `citar` itself since it will be non-trivial and probably introduce more corner cases.

Since reftex is a builtin package @hy-zhao can try to verify if it is indeed a problem with `reftex-all-used-citation-keys` and send a bug report via `M-x report-emacs-bug` if that is the case.

**Comment by hy-zhao** [comment]
Oh yes, I did see the function about reftex you mentioned. And it shows as a void function. Seems so weird.

**Comment by aikrahguzar** [comment]
`symbol's function definition is void: reftex-all-used-citation-keys` means that `reftex-cite` is not loaded. That is actually a problem with `citar`.  `citar-latex` requires `reftex-cite` but if you start emacs open a latex file and the first thing you do is `citar-export-local-bib-file` then you will get that error.

Try this, first insert a citation using `citar-insert-citation` and then try to export evaluate `(reftex-all-used-citation-keys)`, this should be a list of keys. See `gaoEfficientKnowledgeGraph2019` is in that list. If it is not send a bug report using `report-emacs-bug`.

**Comment by bdarcus** [comment]
> I can do a pr but probably not before weekend.

I'll ping you if I can manage time, but it's pretty limited ATM.

I'll tag this with a 1.0 milestone, so we make sure to include the small fix before we tag 1.0.

cc @roshanshariff

**Comment by bdarcus** [comment]
Any chance you have time to fix this @aikrahguzar?

**Comment by bdarcus** [comment]
Partially fixed in #670.

The rest is not our problem :-)

**Comment by hy-zhao** [comment]
Yeah. They sent me an email to solve the bug. Here are steps to follow:

 • Copy the code into into scratch buffer

 • Load your .tex file and hit 'C-c [' to make sure that reftex-cite.el
   is loaded

 • Switch to scratch buffer and eval the function, i.e., put cursor
   after the last parenthesis and hit 'C-x C-e'

 • Switch to your .tex file again and run
   `reftex-all-used-citation-keys'.

```
(defun reftex-all-used-citation-keys ()
  (reftex-access-scan-info)
  (let ((files (reftex-all-document-files)) file keys kk k)
    (save-current-buffer
      (while (setq file (pop files))
        (set-buffer (reftex-get-file-buffer-force file 'mark))
        (save-excursion
          (save-restriction
            (widen)
            (goto-char (point-min))
            (while (re-search-forward
                    (concat "\\(?:^\\|\\=\\)"
                            "\\(?:[^%\n\r]*?\\(?:\\\\%\\)?[^%\n\r]*?\\)"
                            "\\\\\\(bibentry\\|[a-zA-Z]*cite[a-zA-Z]*\\)"
                            "\\(\\[[^]]*\\]\\)?{\\([^}]+\\)}")
                    nil t)
              (setq kk (match-string-no-properties 3))
              (while (string-match "%.*\n?" kk)
                (setq kk (replace-match "" t t kk)))
              (setq kk (split-string kk "[, \t\r\n]+"))
              (while (setq k (pop kk))
                (or (member k keys)
                    (setq keys (cons k keys)))))))))
    (reftex-kill-temporary-buffers)
    keys))
```

**Comment by roshanshariff** [comment]
For future reference, the upstream bug is https://debbugs.gnu.org/cgi/bugreport.cgi?bug=56655.

@hy-zhao Have you checked if the proposed change in that bug report fixes your problem? If so, you might want to reply and tell the maintainer so that the patch can be included in emacs.

**Comment by hy-zhao** [comment]
Yes, it fixed the problem and I already told them. Thanks for reminding!😊
