### ISSUE TITLE
citar-open-notes doesn't open org-roam-capture-template

### ISSUE THREAD

**Issue by LorenRiccie** [emacs-citar/citar#675]
**Describe the bug**

citar-open-notes is not using org-roam capture templates as it does with helm-bibtex or ivy-bibtex.

**Expected behavior**
Currently citar-open-notes opens a note for bibliographic reference without prompting for org-roam capture templates, but instead using a template of its own starting with "Notes on [e.g] Adamson, Interpreting [...]"

**configuration**

> (use-package org-roam
     :ensure t
     :init
    (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory "~/Dropbox/RoamNotes")
    (org-roam-completion-everywhere t)
    (org-roam-capture-templates
      '(("d" "default" plain
	"%?" ;; place of the cursor
	:if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
			              "#+title: ${title}\n#+date: %U\n#+lastmod: Time-stamp: <>\n\n")
	:unnarrowed t)
       ("r" "reference" plain
	"%?"
	:if-new
     (file+head "references/${citekey}.org" "#+title: ${title}\n")
     :immediate-finish t
	:unnarrowed t)))
    :bind
    (("C-c n l" . org-roam-buffer-toggle)
     ("C-c n f" . org-roam-node-find)
     ("C-c n i" . org-roam-node-insert)
     ("C-c n t" . org-roam-tag-add)
     ("C-c n o" . org-id-get-create)
     ("C-M-i"   . completion-at-point))
    :config
    (add-hook 'before-save-hook 'time-stamp)
    (org-roam-db-autosync-mode))

> (org-roam-bibtex-mode +1)

> (use-package citar
     :custom
      (org-cite-global-bibliography '("/Dropbox/bibliography/references.bib"))
      (org-cite-insert-processor 'citar)
      (org-cite-follow-processor 'citar)
      (org-cite-activate-processor 'citar)
      (citar-bibliography org-cite-global-bibliography)
      (citar-notes-paths '("/Dropbox/RoamNotes/references"))
      (citar-library-paths '("/Dropbox/bibliography/bibliography_PDF"))
      :bind
      (:map org-mode-map :package org ("C-c b" . #'org-cite-insert)))

>   (setq citar-open-notes 'orb-citar-edit-note)

>   (use-package citar-embark
     :after citar embark
    :no-require
    :config (citar-embark-mode))

**Emacs version:**
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-28

**Comment by bdarcus** [comment]
It's not a bug; we just changed the note API. See:

https://github.com/emacs-citar/citar/issues/646#issuecomment-1207205635

**Comment by myshevchuk** [comment]
Just for people coming here, see https://github.com/org-roam/org-roam-bibtex/discussions/253

**Comment by bdarcus** [comment]
Do you all think I should just submit `citar-org-roam` to MELPA now-ish?

**Comment by bdarcus** [comment]
Just submitted.
