### ISSUE TITLE
(void-variable hasnotes)

### ISSUE THREAD

**Issue by LorenRiccie** [emacs-citar/citar#676]
Hi @myshevchuk ,

Tried the configuration you mentionned in #646, and get stuck with this error, after `citar-insert-citation`

`Debugger entered--Lisp error: (void-variable hasnotes)
  (gethash citekey hasnotes)`

Any idea?

> Whatever the new Citar API will look like, ORB will support it.

FYI, I'll be tagging 1.0 in the coming days, and then bumping the doom biblio module.

I will post this on the wiki, I think, for folks who want to continue to use ORB:

```elisp
(citar-register-notes-source
 'orb-citar-source
 (list :name "Org-Roam Notes"
        :category 'org-roam-node
        :items #'citar-org-roam--get-candidates
        :hasitems #'citar-org-roam-has-notes
        :open #'citar-org-roam-open-note
        :create #'orb-citar-edit-note
        :annotate #'citar-org-roam--annotate))

(setq citar-notes-source 'orb-citar-source)
```

This relies on https://github.com/emacs-citar/citar-org-roam.

_Originally posted by @bdarcus in https://github.com/emacs-citar/citar/issues/646#issuecomment-1207205635_

**Comment by bdarcus** [comment]
Are you sure you're on very latest version of Citar?

**Comment by LorenRiccie** [comment]
emacs 28.1 and last citar version I think,  20220809.2249.
Isn't it related to citar-org-roam?

**Comment by bdarcus** [comment]
I think only indirectly.

I'll check a thing or two when in front of a computer.

**Comment by bdarcus** [comment]
> I'll check a thing or two when in front of a computer.

So I can't reproduce the error.

The error itself does appear to be coming from [this line](https://github.com/emacs-citar/citar-org-roam/blob/b4b4f1a1d95bb02e33311433dcb6bb652e7368f1/citar-org-roam.el#L74) of `citar-org-roam`.

Do you have `citar-org-roam-mode` activated?
