### ISSUE TITLE
Act on citation in Org Mode keyword or properties

### ISSUE THREAD

**Issue by pprevos** [emacs-citar/citar#684]
**Describe the bug**
When a citation is part of an Org Mode Keyword or a file property and trying to act on the link, Org Mode either opens a new email buffer (due to the @-sign) or it warns "No link found". 

**To Reproduce**
Sample Org Mode file header:

    :PROPERTIES:
    :REFERENCE: [cite:@kauffman_2016_unk]
    :END:
    #+title:      The Unknotting Problem
    #+date:       [2021-07-17 Sat 08:04]
    #+filetags:   :bib:knots:topology:
    #+identifier: 20210717T080455
    #+startup:    inlineimages
    #+reference:  [cite:@kauffman_2016_unk]

**Expected behavior**
The embark buffer appears, as it does when adding a link to the main text. Interestingly, when removing the colon after `reference` in both instances, the expected behaviour occurs.

**Emacs version:**
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-28

**Additional context**
There is an additional problem that I cannot add citations in these locations, but that seems to be prohibited by Org Mode itself.

**Comment by bdarcus** [comment]
This is actually an org issue. Citations aren't allowed/recognized in property drawers.

I understand there are some technical reasons for this; there's some discussion between me and Nicolas in the org list archive.

If you're using org-roam, but suggestion is you just use `@auffman_2016_unk` there, which org-roam will recognize.

**Comment by pprevos** [comment]
I use Denote and am trying to determine the best way to combine it with a bibliography. I used to use Org Roam. Denote does not use a database, which has many advantages, but some disadvantages. Org Roam Bibtex seems to work fine with citations in property drawers.

Interestingly, I can open the citations in these locations as shown above with Org-Ref.

**Comment by bdarcus** [comment]
Right, but those packages no doubt have special code to handle those, since they're not actually citations from an org POV.

We try to defer to org for syntax, parsing, etc.

Actually, the place to put this is probably `citar-embark.el`, since it would just be an embark target-finder.

Are you comfortable trying to figure that out, and possibly submitting a PR?

If not, I can probably do that.

**Comment by pprevos** [comment]
Thanks. I am learning elisp code right now and started toying with denote-citar: https://github.com/pprevos/denote-citar
Lots to learn...

**Comment by bdarcus** [comment]
For now, I've added this to the wiki, and confirmed it works.

https://github.com/emacs-citar/citar/wiki/Embark#new-embark-target-finder-for-bare-org-citation-references

**Comment by pprevos** [comment]
I copied all the code in the wiki, evaluated it and I still get the same behaviour.

The ideal behaviour I am looking for is that when I use `org-open-at-point` on a citation that the embark menu opens irrespective of org context.

It works out-of-the-box when a citation is in the text, but not when the org-context is a keyword (using the `org-element-context` function.

I have a lot to learn ... :)

**Comment by bdarcus** [comment]
Oh yeah, that won't work, because of the restrictions in org itself.

But you can run embark-act directly there.

**Comment by pprevos** [comment]
Are you sure is is an org thing? 

It seems to work fine when I use the org-ref package. When I click on a citation either in a drawer or as a keyword, the hydra menu pops up.

**Comment by bdarcus** [comment]
> When I click on a citation either in a drawer or as a keyword, the hydra menu pops up.

Are you sure that's `org-open-at-point` though?

I'd be surprised.

**Comment by bdarcus** [comment]
@pprevos I added a target finder for the keys in the property drawers. See the linked PR.
