### ISSUE TITLE
`citar-select-multiple` UI tweak

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#686]
@aikrahguzar I loved a subtle little detail in Daniel's vertico-crm prototype:

![image](https://user-images.githubusercontent.com/1134/188695465-83720d19-ee73-4fa1-bead-95b93869f92d.png)

See that `TAB`?

I tried to adapt [the code](https://github.com/minad/vertico/blob/89859e25160b7b80095746beee3ebb0d60cfb6c0/vertico-crm.el#L75) to here, but it's not working as expected.

Any ideas?

It's obviously not a huge priority, but it would make the UI more self-explanatory for new users.

**Comment by aikrahguzar** [comment]
I think the thing to use instead of `vertico-crm-select` is `(car citar--multiple-setup)`. That is supposed to the key used to exit the minibuffer normally.

**Comment by bdarcus** [comment]
Right. I think I'm not understanding the vertico code that generates that output, as this is what I end up with:

![image](https://user-images.githubusercontent.com/1134/188734070-57ec40c0-8f83-48b8-ae7d-f566205e0d24.png)

**Comment by aikrahguzar** [comment]
> Right. I think I'm not understanding the vertico code that generates that output, as this is what I end up with:
> 
> ![image](https://user-images.githubusercontent.com/1134/188734070-57ec40c0-8f83-48b8-ae7d-f566205e0d24.png)

That is because of `substitute-command-keys` which looks for commands in string and replaces them with a key that invokes the command. Here the key is known so something like `(concat "Select Multiple" (propertize (car citar--multiple-setup) ...))` should work.

**Comment by bdarcus** [comment]
Done; thanks!
