### ISSUE TITLE
file parsing: zotero, window paths

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#693]
I guess this the right issue to follow up on...

I use Zotero with ZotFile on Windows to manage PDF's in custom directory. When trying to open a pdf from citar with `citar-open-files`, it is unable to do so, giving me the following (edited a bit) error:

```
None of the files for ‘paperOfInterest2022’ exist; check ‘citar-library-paths’ and ‘citar-file-parser-functions’: ("C\\:\\\\Users\\\\username\\\\Documents\\\\Biblio\\\\Articles\\\\2022\\\\Author_et_al-Paper_of_interest.pdf")
```

While I'm not that familiar with Windows pathnames, I figured out messing on pwsh that drive letter "C\\: ..." is not valid.

In the BIB file (generated with Zotero's BetterBibtex plugin) the field is:

```
@article{articleOfInterest2022,
    ...
    file = {C\:\\Users\\username\\Documents\\Biblio\\Articles\\2022\\articleOfInterst2022.pdf}
}
```

_Originally posted by @allumik in https://github.com/emacs-citar/citar/issues/296#issuecomment-1252336277_

**Comment by bdarcus** [comment]
I created a new issue for this @allumik. I don't really know much at all about Windows though.

**Comment by bdarcus** [comment]
I'm going to ask you to do some research into Emacs and windows file paths. I don't think this is really a citar issue. For example, I suspect if you try to open that file from IELM using something like `find-file`, it will fail. 

Depending on what you find, however, we might be able to tweak something.

**Comment by CVanmarcke** [comment]
Hi bdarcus,
I had the same problem, but managed to fix it with the following code.
I replaced the default parser function (`citar-file--parser-default`) with a function which removes the excess backslashes.
Then I added the changed function to the `citar-file-parser-functions` alist.
Note that this is a quick and dirty fix, no doubt there is a more elegant solution.

```
    (setq citar-file-parser-functions
        '(cv/citar-file--parser-default
          citar-file--parser-triplet))

    (defun cv/citar-file--parser-default (file-field)
      "Replacement function for citar-file-parser default, to handle windows \\"
      (seq-remove
       #'string-empty-p
       (mapcar
        #'string-trim
        (citar-file--split-escaped-string
         (replace-in-string "\\:" ":" 
         (replace-in-string "\\\\" "\\" file-field))
         ?\;))))

    (defun replace-in-string (what with in)
      (replace-regexp-in-string (regexp-quote what) with in nil 'literal))

```

**Comment by roshanshariff** [comment]
Ah, I see we have the [unescape functionality](https://github.com/emacs-citar/citar/blob/24a800be6494cd0c3eac3068a43c4ffcf13d08ea/citar-file.el#L120) in `citar-file--parser-triplet` but not in `citar-file--parser-default`. I'll write up a PR to handle unescaping for both parsers. Thanks for investigating, @CVanmarcke!

**Comment by bdarcus** [comment]
I do wonder why Zotero does that.

**Comment by roshanshariff** [comment]
I'm not sure Zotero can do anything else. They have to escape at least closing braces (for BibTeX fields) and separator characters (`;`), and then also escape the backslashes used to escape those. Perhaps they don't have to escape as many characters as they do, but that doesn't really make a difference for us; we just replace `\<char>` with `<char>` regardless.
