### ISSUE TITLE
Long author name lists and `citar--shorten-names`

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#694]
Very long author lists is not something I deal with in my field, and hence not surprising to see it's an oversight here, but:

- `citar--shorten-names` outputs the entire author list
- when rendering for the minibuffer, this isn't a huge problem, and is actually a benefit, since you can truncate the field width for display, but the full content is still searchable
- but it IS a bit awkward when creating new notes, since there's no way to truncate the list for the title

I'm not sure what the right solution here is, but I do NOT think it is to enable shortening in the main UI.

Perhaps `citar--shorten-names` could take an optional argument to truncate that is only used for notes and the formatted reference, something like this?

```elisp
(defun citar--shorten-names (names &optional truncate and)
  "Return a list of family names from a list of full NAMES.

To better accommodate corporate names, this will only shorten
personal names of the form \"family, given\".

With TRUNCATE, shorten the list of names.

AND is the string to precede the last entry in the list."
  (when (stringp names)
    (let* ((namelist (split-string names " and "))
           (namelen (length namelist))
           (snamelist (when truncate (seq-take namelist truncate)))
           (snamelen (length snamelist))
           (rendered
            (mapconcat
             (lambda (name)
               (if (eq 1 (length name))
                   (cdr (split-string name " "))
                 (car (split-string name ", "))))
             (if truncate snamelist namelist) ", ")))
        (concat rendered
                (when
                    (and truncate (> namelen snamelen)) " et al")))))
```

**Comment by bdarcus** [comment]
I've been struggling how to code this, but just had an idea:

Perhaps could add new template variables like `author-et-al`, which would call `citar--shorten-names` with the `truncate` arg?

**Comment by andersjohansson** [comment]
I like this idea! I stumbled upon the exact same problem when creating a note the other day, where the long author list seemed excessive.

**Comment by bdarcus** [comment]
Any thoughts on this @roshanshariff?

**Comment by roshanshariff** [comment]
I think the idea of having such a "virtual" field is reasonable, and I can imagine others that might make sense (e.g. authors' full names, dates in different formats, etc.). I think it would make sense to have a naming convention for fields like this, so that the code can easily distinguish virtual fields from actual bibtex/CSL-JSON fields that are in the bib entry.

Maybe they could start with a special character or similar?

**Comment by bdarcus** [comment]
I should probably resolve this.

> Maybe they could start with a special character or similar?

Parsebib uses `=`.

I'll see if I can play with some options.

**Comment by bdarcus** [comment]
I merged enhancements to `citar--shorten-names`, but have not yet tackled the rest.

It occurs to me, however, that maybe the way that `citar-display-transform-functions` is designed needs a rethink?

The issue I see is that it's currently only a global association; so anytime you can those template variables, the function is always run.

But it seems like that might be better constrained to the specific template, at least optionally?

Then one could use one type of formatting for minibuffer display, and another for note titles, without needing new pseudo variables.

**Comment by bdarcus** [comment]
Update: the #734 PR branch implements a mechanism to refashion `citar-display-transform-functions`, but I'm rethinking it. The discussion is documented there though.
