### ISSUE TITLE
Citar-select-ref not returning an Alist

### ISSUE THREAD

**Issue by danielclucas** [emacs-citar/citar#696]
When I evaluate the function `(citar-select-ref)` and select a reference from the completion interface what is returned is a string of the citekey, and not a key-value pair as expected.

**Comment by bdarcus** [comment]
We merged a breaking change a couple/few months ago that changes the API to
be citekey-oriented.

Did you just recently update, after a long time not?

**Comment by danielclucas** [comment]
Ah, I see. Thanks for the clarification. I am trying to integrate org-roam's capture functionality with citar per https://jethrokuan.github.io/org-roam-guide/. I am also using your package `citar-org-roam`. I now see why his function `org-roam-node-from-cite` doesn't work as described there. The docstring for `citar-select-ref` includes the statement:
```lisp
A wrapper around `completing-read' that returns (KEY . ENTRY),
where ENTRY is a field-value alist.  Therefore `car' of the
return value is the cite key, and `cdr' is an alist of structured
data.
```
This indicated to me that the function wasn't working as intended. I'll ask my followup in a `citar-org-roam` thread.

**Comment by bdarcus** [comment]
I don't know how we missed correcting that docstring!

I'll fix it.

**Comment by bdarcus** [comment]
> I'll fix it.

Just confirming I fixed this in https://github.com/emacs-citar/citar/commit/52050ca5aeaffa7d08ea3e3cc20042a9bcbeee05.
