### ISSUE TITLE
Citar does not open library file.

### ISSUE THREAD

**Issue by anaxonda** [emacs-citar/citar#700]
**Describe the bug**
running `citar-open-files` does not open library files.

**To Reproduce**
1. run `citar-open-files`. 
2. Select bibtex entry to open library files for. (In this example "chepstow-lustyIncaAgroforestryLessons2000")
3. Error message : `No files for ‘chepstow-lustyIncaAgroforestryLessons2000’ with ‘citar-library-file-extensions’: ("/home/Zotero/storage/Y8T9XDWA/Chepstow-lusty and Winfield - 2000 - Inca agroforestry Lessons from the past.pdf")`
**Expected behavior**
Library file to open. Although citar lists the correct file to open it does not open it.
**Emacs version:**
v 29.0.50 
 and doom:
```
Doom core     v3.0.0-pre       HEAD -> master 9f22a0a2a 2022-10-07 19:48:23 +0200
Doom modules  v22.10.0-pre     HEAD -> master 9f22a0a2a 2022-10-07 19:48:23 +0200
```

**Additional context**
citar config:

```
(use-package! citar
        :config
        (setq citar-notes-paths '("/home/Documents/org")
citar-library-paths '("/home/Documents/library" "/home/Zotero/storage")
citar-bibliography '("/home/Documents/Reference/masterlib.bib" "/home/Documents/library/catalog.bib")
citar-open-note-function 'orb-citar-edit-note
citar-library-file-extensions '(".pdf " ".epub" ".djvu")
citar-file-parser-functions '(citar-file--parser-default citar-file--parser-triplet)
)

  ;; (setq citar-notes-source 'orb-citar-source)
         )
```

When I try the function `citar-open` the library files are not listed for a given key.

**Comment by bdarcus** [comment]
Also, note that your config for org-roam is out of date; we changed the note API a couple/few months ago. See https://github.com/emacs-citar/citar/wiki/Notes-configuration#org-roam-bibtex.

**Comment by anaxonda** [comment]
> Is that path in the bib entry?

Yes, here is the corresponding file field in the bibtex file: `file = {../../Zotero/storage/Y8T9XDWA/Chepstow-lusty and Winfield - 2000 - Inca agroforestry Lessons from the past.pdf}`



> Also, note that your config for org-roam is out of date; we changed the note API a couple/few months ago. See https://github.com/emacs-citar/citar/wiki/Notes-configuration#org-roam-bibtex.

Ah, thanks. I did follow that guide and have ORB working but did not remove the old `citar-open-note-function`






> And this should not include the leading dots, though I don't know if that has any impact here.
> 
> ```emacs-lisp
> citar-library-file-extensions '(".pdf " ".epub" ".djvu")
> ```
> 
> You can also just remove that, and it will accept any extension.

Ah, success when I set `citar-library-file-extensions` to nil! Guess I'll just leave it as that for now.
