### ISSUE TITLE
Function for updating metadata

### ISSUE THREAD

**Issue by apc** [emacs-citar/citar#701]
**Is your feature request related to a problem? Please describe.**
The wiki contains a function for updating PDF metadata for a file associated with a citation key using the bibliographic information associated with that key. That function no longer works with citar.

I have something that seems to work but it needs some work, so I'm putting it up here in case anyone has suggestions on how to improve.

```elisp
(defun my/citar-update-pdf-metadata (citekey)
(interactive (list (citar-select-ref)))
  (citar--check-configuration 'citar-library-paths)
  (unless citar-library-paths
    (user-error "Make sure `citar-library-paths' is non-nil"))
  (let* ((files (gethash cite-key (citar-get-files cite-key))))
    (unless files
      (user-error (format "There are no PDF files associated with %s" citekey)))
    (let ((file (or (unless (cdr files) (car files)) (completing-read "Please select a PDF file: " files)))
          (title (citar-get-value 'title citekey))
          (author (cond ((citar-get-value 'author citekey)
                        (citar-get-value 'author citekey))
                        ((citar-get-value 'editor citekey)
                         (concat (citar-get-value 'editor citekey) " (ed.)")))))
      (progn
        (copy-file file my/bib-library-backup-path 1)
        (call-process-shell-command
         (concat "exiftool -overwrite_original_in_place -Title='" title "' -Author='" author "' " file))))))
```

If anyone can point me in the direction for turning this into something that would be useful for different use cases, I can happily try to work on a version that could eventually go up on the wiki.

**Comment by bdarcus** [comment]
Feel free to just put it on the wiki. It's the place for not-fully-formed ideas and code, and at least it works ;-)

I don't really have any suggestions; it looks good to me, but I'm not the best programmer.
