### ISSUE TITLE
`citar-copy-reference` slow?

### ISSUE THREAD

**Issue by benthamite** [emacs-citar/citar#702]
Thanks for this great package.

I noticed that it takes Emacs 5–7 seconds after I invoke `citar-copy-reference` to actually copy the formatted reference to the kill ring. Emacs runs generally pretty fast on my current machine and I very rarely notice these sorts of delays, so I was wondering if this behavior is normal or if there is something that could be done to improve performance (this wouldn't normally bother me, but I use `citar-copy-reference` dozens of times per day on average). I attach a profiler report, in case it helps, and the relevant parts of my config follow.

[profiler.txt](https://github.com/emacs-citar/citar/files/9804546/profiler.txt)

``` emacs-lisp
(use-package oc
  :demand t
  :custom
  (org-cite-global-bibliography `(,ps/file-bibliography))
  (org-cite-csl-styles-dir ps/dir-csl-styles)
  (org-cite-csl-locales-dir ps/dir-csl-locales)
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar) ; `org-open-at-point` integration
  (org-cite-activate-processor 'citar))

(use-package citar
  :straight (citar :type git :host github :repo "emacs-citar/citar" :includes (citar-org))
  :demand t
  :after (oc vertico embark marginalia citeproc)
  :custom
  (citar-open-note-functions '(orb-citar-edit-note))
  (citar-bibliography org-cite-global-bibliography)
  (citar-notes-paths `(,ps/dir-bibliographic-notes))
  (citar-at-point-function 'embark-act)
  (citar-symbols
   `((file ,(all-the-icons-faicon "file-o" :face 'all-the-icons-green :v-adjust -0.1) . " ")
     (note ,(all-the-icons-material "speaker_notes" :face 'all-the-icons-blue :v-adjust -0.3) . " ")
     (link ,(all-the-icons-octicon "link" :face 'all-the-icons-orange :v-adjust 0.01) . " ")))
  (citar-symbol-separator "  ")
  (citar-format-reference-function 'citar-citeproc-format-reference))

(use-package citar-citeproc
  :after citar
  :demand t
  :custom
  (citar-citeproc-csl-styles-dir org-cite-csl-styles-dir)
  (citar-citeproc-csl-locales-dir org-cite-csl-locales-dir))

```

**Comment by bdarcus** [comment]
> I noticed that it takes Emacs 5–7 seconds after I invoke `citar-copy-reference` to actually copy the formatted reference to the kill ring.

Is that for a single reference?

Here's what I see from IELM, on my laptop, running Emacs 28.1.

```elisp
ELISP> (benchmark-run-compiled (citar-copy-reference (list "toly2017")))
(0.319477116 1 0.12375739799999863)
```

**Comment by benthamite** [comment]
Thanks. Yes, just a single reference.

``` emacs-lisp
(benchmark-run-compiled (citar-copy-reference '("Balintona2022CitationsOrgmodeOrgcite")))
(3.12648 0 0.0)
```

Less than 5–7 seconds, but still 10x what it took in your system.

**Comment by benthamite** [comment]
Ah, the reason is now pretty clear: my bibtex file has +14k entries. When I try it on a separate file I use for newly added entries, containing less than 100 items, the results are instantaneous. I didn't think of this since oc/citar is otherwise very fast once the big bibtext file is loaded.

**Comment by bdarcus** [comment]
That would explain it, in which case `citeproc-el` is parsing the file each time, I'd guess.

@andras-simonyi a few months back added support for `citeproc-el` to access references from the citar cache. I don't recall if it requires some configuration for that to work, but if it does, we might add a note about that here.

**Comment by andras-simonyi** [comment]
> I thought @andras-simonyi a few months back added support for `citeproc-el` to access references from the citar cache. [...] seems he added it to the `oc-csl-activate` processor. That makes sense, since citeproc needs access to more structured data than citar. Would be nice for us to figure this out, however.

Yes, using the citar cache would be the easy fix speed-wise, but the generated citations could lack some metadata which is dropped by Citar.

**Comment by bdarcus** [comment]
> Yes, using the cache directly as it is done in `oc-csl-activate`would be the easy fix speed-wise, but the generated citations could lack some metadata which is dropped by Citar. Is the list of dropped fields configurable somehow?

Right now, we just use the `parsebib` display paremeter when parsing files.

But perhaps it would be better not to do that, and instead store the more structured data in the cache?

Any thoughts @roshanshariff?

**Comment by roshanshariff** [comment]
I suppose the problem isn't just the "more structured" data (we could choose to store the raw data in the cache) but rather that we only parse fields that show up in the display template. So, for example, the publisher field wouldn't be parsed whereas citeproc styles presumably need it to be?

For this specific use case, I wonder if it makes sense to make a citeproc source that doesn't parse the entire bibtex file, but rather only looks for and parses entries as needed (so the cited entries and any cross-references). Perhaps that can be done faster.

**Comment by bdarcus** [comment]
Yes, your observation in the first paragraph is correct.

WDYM a "citeproc source"? A separate hash table?

**Comment by roshanshariff** [comment]
From what I remember, citeproc calls a given for each key for which it needs bibliographic information. The "standard" implementation just parses the bib file into a hash table, then looks up the key in it. The new implementation by @andras-simonyi made the function look in Citar's cache instead.

I was thinking it might be possible to make another implementation that just opens the bib file in a buffer, uses a regexp to find each entry as-needed, and just parses the entry at-point (and presumably recursively for cross-referenced entries).

**Comment by andersjohansson** [comment]
I started out following @roshanshariff’s suggestion in the draft pull request, but only for json (which I use, exported from Zotero) and without considering crossref at all.

This works great and fast for my use case but is of course not complete.

**Comment by andras-simonyi** [comment]
First of all, sorry for reacting only now. The suggestion and work by @roshanshariff  and @andersjohansson to implement a search-based itemgetter is spot on, in fact, historically, the first itemgetters in citeproc were of this type. I think the main difficulty in this direction is implementing Bib(la)TeX string abbreviation and crossref resolution -- it'd be reasonable to try to use parsebib as much as possible as it has already implemented the necessary functions, but it might require some refactoring on the parsebib side.

**Comment by bdarcus** [comment]
@benthamite I merged a fix for this. Let me know?

**Comment by benthamite** [comment]
@bdarcus Great, thank you!
