### ISSUE TITLE
`citar--select-resource` and `citar--open-resource` strip text properties from selections -- why?

### ISSUE THREAD

**Issue by Hugo-Heagren** [emacs-citar/citar#705]
(Thanks for you work in #704 -- this is related to #703)

**Describe the bug**
`citar--select-resource` and `citar--open-resource` both strip text properties from selected candidates before running user-defined functions on them. This makes it impossible for those functions to rely on text properties to store information (such as org-roam ids, which would make it much easier to write an org-roam notes backend).

Is there a good reason to do this? If not could we remove this 

**To Reproduce**
Relevant code (note use of `substring-no-properties`:

https://github.com/emacs-citar/citar/blob/24a800be6494cd0c3eac3068a43c4ffcf13d08ea/citar.el#L732

https://github.com/emacs-citar/citar/blob/24a800be6494cd0c3eac3068a43c4ffcf13d08ea/citar.el#L1269

There isn't really any behaviour to reproduce, but here's my config at the moment, as a demonstration of why this is relevant:

```emacs lisp
(require 'cl-lib)
(require 'org-roam)

(defun my/citar-org-roam-has-notes ()
  (lambda (key) (org-roam-node-from-ref (concat "@" key))))

(defun my/citar-get-org-roam-notes (keys)
  (let ((table (make-hash-table)))
    (mapcar
     (lambda (key)
       (when-let ((node (org-roam-node-from-ref (concat "@" key)))
		  (id (org-roam-node-id node))
		  (formatted (org-roam-node-formatted node)))
	 (puthash key `(,(propertize formatted 'org-roam-node-id id)) table)))
     keys)
    table))

(defun my/citar-open-org-roam-note (note)
  "Capture to the Org Roam node with id stored in NOTE.
The relevant id should be stored in a text property
  `org-roam-node-id' in the string NOTE."
  (setq foo note)
  (when-let ((id (get-text-property 1 'org-roam-node-id note))
	     (node (org-roam-node-from-id id)))
    (org-roam-capture- :node node)))

(defun my/citar-capture-org-roam (key entry)
  (let ((title (citar-format--entry "${title}" entry)))
    (org-roam-capture-
     :templates
     `(("d" "reference" plain "%?" :if-new
	(file+head
	 ,(concat "%<%Y%m%d%H%M%S>-${slug}-" key ".org")
	 ,(concat ":PROPERTIES:
:ROAM_REFS: @" key "
:END:
#+title: ${title}\n"))
	:unnarrowed t))
     :props '(:finalize find-file)
     :node (org-roam-node-create :title title))))

(citar-register-notes-source
 'my/citar-org-roam
 (list :name "Org-Roam Notes"
       :category 'org-roam-node
       :hasitems #'my/citar-org-roam-has-notes
       :open #'my/citar-open-org-roam-note
       :items #'my/citar-get-org-roam-notes
       :create #'my/citar-capture-org-roam))

```

**Expected behavior**
The above fails to open already-existing notes (e.g. from `citar-open`). The notes are dispalyed correctly (that is the formatted string from the `formatted` var in `my/citar-get-org-roam-notes` is displayed), but because the string has had its properties removed, once this is passed to `my/citar-open-org-roam-note`, it can't get the roam node id.

Worth mentioning that it *does* work exactly as I would want, when I remove `substring-no-properties` from the two places noted above and reevaluate the function definitions. That's the only change needed.

**Emacs version:**
29.0.5

**Additional context**
Worth mentioning that this is only really a problem because of how I happen to want my notes backend to work -- I don't think this is a significant problem with citar in general, but it does constrain user-defined custom functionality a bit.

**Comment by bdarcus** [comment]
> Is there a good reason to do this?

I'll need to look again more closely to see if I can better answer your question.

I know there's a reason (bugs without it), but I don't recall the exact reason, or if there's other workarounds.

**Comment by bdarcus** [comment]
Looking just now, I think @roshanshariff added that, and my initial tests show `citar-open` works fine without it.

@roshanshariff - I added a commit to remove this to #704. Is that OK, or are we missing something?

**Comment by roshanshariff** [comment]
I believe this has to do with Embark, which tries to act like `completing-read` in removing text properties from text injected into minibuffer prompts. I seem to remember that I removed the text properties anyway to make the Embark and non-Embark cases behave the same, so we don't accidentally introduce a bug by depending on the properties surviving.

This is effectively the same reason we have to mess around with adding invisible citekeys to completion candidates in `citar-select-resource`.

**Comment by bdarcus** [comment]
So to be clear, I should drop that commit; correct?

**Comment by roshanshariff** [comment]
@bdarcus, yes, unfortunately. I'm afraid we can't rely on text properties if we want to work with Embark (and Embark can't retain text properties to maintain compatibility with `completing-read`).

**Comment by bdarcus** [comment]
OK, I removed that commit.

Sorry @Hugo-Heagren; you'll have to find another way, since compatibility with Embark is a high priority. This is why, per Roshan, we used the "brittle" approach you mentioned.

**Comment by Hugo-Heagren** [comment]
> OK, I removed that commit.
> 
> Sorry @Hugo-Heagren; you'll have to find another way, since compatibility with Embark is a high priority. This is why, per Roshan, we used the "brittle" approach you mentioned in `citar-org-roam` (and even here).

Alright, thanks for investigating. I'll have a look into alternatives when I have some time -- I have a feeling I might end up suggesting a slightl revision of the notes api to accomodate cases like this, would that be welcome?

**Comment by bdarcus** [comment]
> I might end up suggesting a slightl revision of the notes api to accomodate cases like this, would that be welcome?

In general, suggestions always welcome.

**Comment by Hugo-Heagren** [comment]
> Can you explain what you're trying to do here, that's different than citar-org-roam? I might be able to offer a suggestion or two.

Great, thanks.

I want to use org roam to store notes for items in my bibliography, and access them with citar. when *do* access them, I want to use org-roam's capture system to open thenotes, or create new ones if necessary. All of that is supported by org-roam-citar. 

Finally, in dialogues such as selecting a resource in `citar-open`, I want the notes to appear in the same way that they would in org-roam's own completing-read interface. In particular, I don't want to have to include the id, file name or slug in the of the org roam node in the text of the completing-read interface. This is what I was trying to achieve with text properties above (and I believe citar-org-roam does not achieve). I recognise though that this is a pretty small thing!

Maybe some sort of user-configurable transformation function to *and* from certain strings would help achieve this?

**Comment by bdarcus** [comment]
> I want the notes to appear in the same way that they would in org-roam's own completing-read interface. In particular, I don't want to have to include the id, file name or slug in the of the org roam node in the text of the completing-read interface. This is what I was trying to achieve with text properties above (and I believe citar-org-roam does not achieve). I recognise though that this is a pretty small thing!
> 
> Maybe some sort of user-configurable transformation function to _and_ from certain strings would help achieve this?

I need to document `:transform` in #704; it seems from the default notes source, it does just that?

```elisp
    :transform #'file-name-nondirectory))
```

But ...

So you just want a different UI display?

If yes, can't you just use a different annotation function then? Or maybe we can have a template for that in `citar-org-roam`?

To summarize:

1. The completing-read candidates for `citar-org-roam` are just `CITEKEY ROAM_ID`; but only the first is visible. This assures the data we need to act on the candidates is there, and also that the candidate strings are unique.
2. The rest of the display is handled by the annotation function.
3. The downside in general of 2 is annotations aren't part of the candidate; they are just for display.
4. I have thought about ditching 2, and putting all content in the candidate string, which could allow us to use a citar template for it, and also avoids 3. 
5. I agree it probably makes sense to make this configurable in some way.

Aside: this might be better discussed at that repo, as the issues you are raising are more general re: that project, but really specific to it.

**Comment by Hugo-Heagren** [comment]
Thanks! This was really useful. In short, yes, I wanted a different UI display. I didn't realise exactly how `:transform` worked, but I've got it setup now in the way that I wanted. I'd be happy to leave my config on the wiki if that would be useful, though with citar-org-roam it might not be?

Thanks again!

**Comment by bdarcus** [comment]
> I'd be happy to leave my config on the wiki if that would be useful, though with citar-org-roam it might not be?

I kind of think, if in doubt, just put it there; it may well be useful for people. I'm also curious!
