### ISSUE TITLE
RETURN has no effect in citar minibuffer

### ISSUE THREAD

**Issue by JonatanSahar** [emacs-citar/citar#707]
Hi, 
I've updated Doom, and now I can't use citar since hitting `return` doesn't do anything... 
Very strange. 
Do you have any ideas?

Thanks!

**Comment by bdarcus** [comment]
Can you provide more details? RETURN in what context?

**Comment by JonatanSahar** [comment]
Yes, sorry - in the contex of `citar-open` when browsing references. 
I can still call embark-act, but the default action of opening the list of associated resources is gone.

**Comment by bdarcus** [comment]
So you mean:

1. `M-x citar-open`
2. go to preferred candidate
3. hit `RETURN`; nothing happens?

If yes, I'm not really sure, as I don't see that, and I use Doom.

**Comment by JonatanSahar** [comment]
Exactly. And the same for `org-cite-insert`. 
I just noticed that the prompt also says 'select multiple` at the top, although I didn't configure the advice that's described in the docs... 
TAB does add to the selection, but RETURN still does soen nothing.

**Comment by bdarcus** [comment]
The advice that we previously suggested in the README is no longer valid, as that code was removed from consult. We reimplemented here, however, so that `TAB` should select/deselect, and `RET` should complete.

I don't think it's a citar issue. Perhaps something with your Doom config?

**Comment by JonatanSahar** [comment]
that is so strange.. I have:
`RET (translated from <return>) runs the command citar--multiple-exit, which is
an interactive compiled Lisp function in ‘citar.el’.

It is bound to RET.

(citar--multiple-exit)

Exit with the currently selected candidates.
`

for `describe-key` on `RET`, which seems right I guess(?) but still does nothing...

**Comment by JonatanSahar** [comment]
I suppose it could be something with my config, though I can't imagin what it would be.. it started after updating doom and all the packages recently

**Comment by bdarcus** [comment]
Maybe try recompiling and restarting?

**Comment by JonatanSahar** [comment]
recompiling which part?

**Comment by bdarcus** [comment]
For doom, maybe the whole straight directory? I sometimes just delete it
and run doom sync.

You might check on the doom discord/discourse?

**Comment by bdarcus** [comment]
You're using the vertico module, @JonatanSahar?

#708 reports similar, but in default completion.

**Comment by aikrahguzar** [comment]
@JonatanSahar, I am on the latest commit of doom and everything seems to be working for me. Do you see any message with a warning or error when you press `RET`? You can also check `view-lossage` bound to `SPC h l` by default after a citar command to see what was run when you pressed `RET` but it would be very weird if it was different from what was shown by `describe-key`.

**Comment by JonatanSahar** [comment]
> You're using the vertico module, @JonatanSahar?
> 
> #708 reports similar, but in default completion.

I am using vertico.



> @JonatanSahar, I am on the latest commit of doom and everything seems to be working for me. Do you see any message with a warning or error when you press `RET`? You can also check `view-lossage` bound to `SPC h l` by default after a citar command to see what was run when you pressed `RET` but it would be very weird if it was different from what was shown by `describe-key`.

` SPC n b             ;; citar-open
 j                   ;; self-insert-command
 C-j                 ;; vertico-next
 C-j                 ;; vertico-next
 C-j                 ;; vertico-next
 <return>            ;; citar--multiple-exit
 TAB                 ;; better-jumper-jump-forward
 <escape>            ;; abort-recursive-edit
 SPC h l             ;; view-lossage
`

That's a neat command, I didn't know it.

**Comment by JonatanSahar** [comment]
> For doom, maybe the whole straight directory? I sometimes just delete it and run doom sync. You might check on the doom discord/discourse?

I'll give it a shot, thanks!

**Comment by aikrahguzar** [comment]
I see the problem here but not why it is happening here, it is basically

> TAB ;; better-jumper-jump-forward 

while `TAB` should be bound to `vertico-exit` and it is for me. Does 

``` emacs-lisp
(setq citar--multiple-setup ("<tab>" . "RET"))
```
help?

I don't quite understand "TAB" vs "<tab>" except that it has something to do with gui vs terminal and I only use gui.

BTW I only see `better-jumper-jump-forward` bound to "<C-i>" (which has something to do with `TAB` on terminals) on `evil-motion-state-map`. Do you have evil enabled in minibuffer?

**Comment by JonatanSahar** [comment]
Hi, I appreciate your trying to help :)
I have `C-i` bound to `better-jumper-jump-forward` in general (i.e. not in a specific map) so it should "take" wherever it's not already bound... I'll try to disable it an see if it makes a difference. 
Your snipped produced an error: 
> eval: Wrong type argument: listp, "RET"

**Comment by aikrahguzar** [comment]
> Hi, I appreciate your trying to help :) I have `C-i` bound to `better-jumper-jump-forward` in general (i.e. not in a specific map) so it should "take" wherever it's not already bound... I'll try to disable it an see if it makes a difference. 

This is very confusing. The biding to `vertico-exit` that should have triggered is on the local map but any binding on the global map doesn't matter. You also say that `<tab>` works for selection so it seems like it the binding for `vertico-exit` is in effect. Can you post the result of what you see in `view-lossage` if you start a citar command, press TAB to select and candidate and then RET to exit. 

Also is the issue specific to terminal or you see it both in terminal and gui emacs.

> Your snipped produced an error:
> 
> > eval: Wrong type argument: listp, "RET"

I had a missing quote but I thought I had corrected after a few minutes. I see some weirdness with markup too but this should do the same thing and doesn't need a quote,
```emacs-lisp
(setq citar--multiple-setup (cons "<tab>"  "RET"))
```

**Comment by JonatanSahar** [comment]
>  SPC n b ;; citar-open ;; 
>  C-j ;; vertico-next ;; 
>  <tab> ;; vertico-exit ;; 
>  <return> ;; citar--multiple-exit ;; 
>  TAB ;; better-jumper-jump-forward ;; 
>  <escape> ;; abort-recursive-edit ;; 

That's really strange - I didn't press that TAB only the first <tab>
> 

> ```emacs-lisp
> (setq citar--multiple-setup (cons "<tab>"  "RET"))
> ```

That works! What does it do?

**Comment by aikrahguzar** [comment]
> That's really strange - I didn't press that `TAB` only the first `<tab>`

Basically  `TAB` is pressed for you by `citar--multiple-exit`.

>> ```emacs-lisp (setq citar--multiple-setup (cons "<tab>" "RET")) ```

> That works! What does it do?

It basically tells `citar--multiple-exit` to emit `<tab>` instead of `TAB`.

But `<tab>` vs `TAB` is one of the great mysteries of life. For reasons beyond my understanding what is happening is that when citar tries of bind `TAB`, what is actually bound in your case is `<tab>` and there is no local binding for `TAB`. But `citar--multiple-exit` still emits `TAB` which is then falls through to the global map but they binding for it probably does nothing in minibuffer.

@bdarcus both `<tab>` and `TAB` work for me so maybe we should change the default for `citar--multiple-setup`? I don't know enough of the distinction to know if that will also cause similar problems in other scenarios.

**Comment by bdarcus** [comment]
Might the distinction have something to do with platforms?

@JonatanSahar any chance you're on Mac OS or Windows?

In any case:

> ... both <tab> and TAB work for me so maybe we should change the default for citar--multiple-setup? I don't know enough of the distinction to know if that will also cause similar problems in other scenarios.

Does this thread tell us anything useful? 

https://emacs.stackexchange.com/questions/9631/what-is-the-difference-between-tab-and-tab

**Comment by JonatanSahar** [comment]
I'm on windows in fact! Sorry, I neglected to mention it..

**Comment by aikrahguzar** [comment]
> Does this thread tell us anything useful?
> 
> https://emacs.stackexchange.com/questions/9631/what-is-the-difference-between-tab-and-tab
> 
> And this comment in the linked issue:
> 
> [syl20bnr/spacemacs#4024 (comment)](https://github.com/syl20bnr/spacemacs/issues/4024#issuecomment-161122099)

I am still very confused. The answer says that if both `<tab>` and `TAB` are bound, `<tab>` is not translated to `TAB`. But as far as I see all the bindings are for `TAB` and I don't know why a binding for `TAB` ends up as one for `<tab>`.

**Comment by aikrahguzar** [comment]
@JonatanSahar , can you please do the following,
1) Evaluate
    ```emacs-lisp
    (defvar citar--debug nil)

     (defun citar--setup-multiple-keymap ()
         "Make a keymap suitable for `citar--select-multiple'."
       (let ((keymap (make-composed-keymap nil (current-local-map)))
             (kbdselect (kbd (car citar--multiple-setup)))
             (kbdexit (kbd (cdr citar--multiple-setup))))
          (define-key keymap kbdselect (lookup-key keymap kbdexit))
          (define-key keymap kbdexit #'citar--multiple-exit)
          (use-local-map keymap))
       (setq citar--debug (current-local-map)))
    ```
2)  Evalaute
     ```emacs-lisp
    (setq citar--multiple-setup (cons "TAB"  "RET"))
    ```
    Use a citar command afterwards and check the value of `citar--debug` and post the bindings for `<tab>` and `TAB` here.

3) Evalaute
    ```emacs-lisp
       (setq citar--multiple-setup (cons "<tab>"  "RET"))
    ```
    Use a citar command afterwards and check the value of `citar--debug` and post the bindings for `<tab>` and `TAB` here.

FWIW, this is what I see:
1) With `TAB`
    ```
    TAB                 exit-minibuffer
    TAB                 self-insert-command
    TAB                 vertico-insert
    ```
2) With `<tab>`
    ```
   <tab>               exit-minibuffer
   TAB                 self-insert-command
   TAB                 vertico-insert
   ```

**Comment by bdarcus** [comment]
> I am still very confused. The answer says that if both `<tab>` and `TAB` are bound, `<tab>` is not translated to `TAB`. But as far as I see all the bindings are for `TAB` and I don't know why a binding for `TAB` ends up as one for `<tab>`.

It also seemed notable to me the distinction between GUI and terminal.

**Comment by bdarcus** [comment]
What's the status of this issue, @JonatanSahar? Can we close it?

**Comment by JonatanSahar** [comment]
Yes! That actually solves it!
Thanks a lot for your help.
