### ISSUE TITLE
Automatically add filetags when creating org-roam node

### ISSUE THREAD

**Issue by djs42012** [emacs-citar/citar#711]
**Is your feature request related to a problem? Please describe.**
It's currently difficult to automate the addition of tags to org-roam nodes crated by Citar

**Describe the solution you'd like**
A variable or a function that can be advised to automatically tag a node once it's created (e.g. `#+FILETAGS: literature`)

**Describe alternatives you've considered**
Previously I had been using some code to accomplish this, but now the snippet no longer works.
``` lisp
(defun djs-org-roam-insert-literature-tag ()
    "inserts a hard coded filetag for literature notes in org roam"
    (let ((node (org-roam-node-at-point 'assert)))
      (save-excursion
        (goto-char (org-roam-node-point node))
        (if (= (org-outline-level) 0)
            (let ((current-tags (split-string (or (cadr (assoc "FILETAGS"
                                                               (org-collect-keywords '("filetags"))))
                                                  "")
                                              ":" 'omit-nulls)))
              (org-roam-set-keyword "filetags" (org-make-tag-string (seq-uniq (append '("literature")  current-tags)))))
          (org-set-tags (seq-uniq (append '("literature") (org-get-tags)))))
        )))
  (defadvice! citar-add-literature-tag (&rest _)
    "Add literature tag to newly created org-roam node"
    :after #'citar-org-format-note-default
    (djs-org-roam-insert-literature-tag))
  )

```

**Additional context**
Any way to conveniently automate the addition of tags to newly created nodes, so that they don't get missed by my other infrastructure would be tremendous

**Comment by bdarcus** [comment]
I haven't really thought about this, but cannot one now use a `tags` or `keywords` template variable to at least grab that string?

**Comment by djs42012** [comment]
> cannot one now use a `tags` or `keywords` template variable to at least grab that string?
 
 I’m sorry, I don’t understand what you mean. Which templates are you referring to?

**Comment by bdarcus** [comment]
The citar ones that govern, for example, the basic display, note titles, etc.

**Comment by djs42012** [comment]
> The citar ones that govern, for example, the basic display, note titles, etc. See `citar-templates`.

I'm a little confused on how to use these. Currently I am trying to implement this by doing the following:
```lisp
setq citar-note-format-function #'djs-citar-org-format-note-default)
```

Where I have defined:
```lisp
(defun djs-citar-org-format-note-default (key entry)
    "Custom create note template"
    (let* ((template (citar--get-template 'note))
           (note-meta (when template
                        (citar-format--entry template entry)))
           (filepath (expand-file-name
                      (concat key ".org")
                      (car citar-notes-paths)))
           (buffer (find-file filepath)))
      (with-current-buffer buffer
        ;; This just overrides other template insertion.
        (erase-buffer)
        (insert "TESTING")
        (citar-org-roam-make-preamble key)
        (when template (insert note-meta))
        (when template (insert filepath))
        (search-backward "|")
        (delete-char 1)
        (when (fboundp 'evil-insert)
          (evil-insert 1)))))
```
Currently though, I am not seeing any differences between what I am attempting to define and the previous default behavior.

Even the original `citar-org-format-note-default` contained a line  `(insert "\n\n|\n\n#+print_bibliography:")`, which was not getting added when I created a note, so I am not quite sure if/how this function is getting called.

**Comment by bdarcus** [comment]
While I haven't tested it, I was really wondering if you could just modify the note template, and keep the default function. Hopefully the below illustrates the idea?

```elisp
(citar-format--entry "${title}\n#+FILETAGS:  ${keywords tags}" (citar-get-entry "isin2002"))
```

The default note format is just this:

```elisp
"Notes on ${author editor}, ${title}"
```

... and the function places that in the title property. But I'm thinking if you modify it like so, it might just work?

```elisp
"Notes on ${author editor}, ${title}\n#+FILETAGS:  ${keywords tags}"
```

**Comment by djs42012** [comment]
So I'm running into `Error in post-command-hook (yas--post-command-handler): (wrong-type-argument markerp 77)` when I create a note now.

I was able to get some of the desired behavior by setting `citar-org-roam-note-title-template "${author} - ${title}\n#+filetags: :literature:"`, but am experiencing weird behavior when I create a node.
The `#+title:` tag is getting added twice, creating this unintended display
![2022-11-06-145650_231x27_scrot](https://user-images.githubusercontent.com/93899859/200197346-989fc93b-3300-4b5d-badf-977af44202f9.png)

I tried updating `citar-templates` according to your advice:
```list
citar-templates '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
                           (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords keywords:*}")
                           (preview . "${author editor} (${year issued date}) ${title}, \
${journal journaltitle publisher container-title collection-title}.\n")
                           (note . "${author} - ${title}\n#+FILETAGS literature"))
```
But I think due to this other error, none of my changes are coming into effect

**Comment by djs42012** [comment]
I think I have to rescind my last reply and potentially close the issue. I think the doubling of `#+title` was solved by restarting my daemon. Here is the configuration that produces the desired output:
```lisp
(setq citar-org-roam-note-title-template "${author} - ${title}\n#+filetags: :literature:"
         citar-symbols `((file ,(all-the-icons-faicon "file-o" :face 'all-the-icons-green :v-adjust -0.1) .
                          " " )
                         (note ,(all-the-icons-material "speaker_notes" :face 'all-the-icons-blue :v-adjust -0.3) .
                               " ")
                         (link ,(all-the-icons-octicon "link" :face 'all-the-icons-orange :v-adjust 0.01) .
                               " "))

         citar-templates '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
                           (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords keywords:*}")
                           (preview . "${author editor} (${year issued date}) ${title}, \
${journal journaltitle publisher container-title collection-title}.\n")
                           (note . "${author} - ${title}\n#+FILETAGS literature"))
         ))
 ```
What I don't understand is that if I comment out my changes  to `citar-org-roam-note-title-template`, then the equivalent text which I put in `citar-templates` still does not come into effect. In other words, I am not sure why I cannot make the desired change just through `citar-templates` and have to rely on `citar-org-roam-note-title-template`, but I am able to accomplish what I want.

**Comment by bdarcus** [comment]
Looking at the code, because of this line:

https://github.com/emacs-citar/citar-org-roam/blob/27105d0a9578279560cd79cfad5871e7e603bc58/citar-org-roam.el#L175

E.g. citar-org-roam ignores the `citar-templates` note template.

Not sure; maybe that was a bad idea, and we should change it?

Glad you have it working though!

**Comment by djs42012** [comment]
Great! Thanks again for all your help. I think it's nice to have the separate variable, especially now that you've pointed me to the right part of the codebase!
