### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by aagon** [emacs-citar/citar#712]
Hello,

First of all, thank you for this very useful library. I am in the process of packaging it for debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017683), and I need a little clarification regarding the licence status of test/manual/*. Indeed, the exact licence of every file in a debian package must be known and documented for the package to be accepted.

You seem to have adapted them from @raxod502, more precisely from https://github.com/raxod502/selectrum/tree/master/test. They had been licenced under the MIT licence, and the copyright holder was Radian LLC. The MIT licence requires preservation of the licence in all "copies or substantial portions of the Software".

On the other hand, the citar repository is licenced under the GPL-3+, and includes these files. As a consequence, I am not entirely sure as to what exact licence these files are distributed under : 
- MIT, to Radian LLC ?
- GPL-3+, to Bruce D'Arcus ?
- both, i.e. dual licencing ?

I have taken the liberty of including @raxod502 in the conversation, since I am not even sure who gets to decide.

Thank you in advance for your time.

Best,

Aymeric Agon-Rambosson

**Comment by bdarcus** [comment]
I hadn't even thought about that, but good questions.

Could you just omit those files from your package?

**Comment by minad** [comment]
@bdarcus The files in @raxod502's directory are licensed under MIT. But given that I authored them, I am happy to relicense them under GPL-3+.

**Comment by minad** [comment]
My recommendation is to remove the header "adapted from", to avoid any confusion. Instead add an SPDX license header.

**Comment by bdarcus** [comment]
OK, thanks @minad; will do!

**Comment by bdarcus** [comment]
Would I put you as the copyright holder in that case, @minad?

**Comment by minad** [comment]
It is not relevant in this case given the triviality of the code and in particular given that I've contributed before to Citar. 

Generally all the contributors of your project still hold the copyright of the code they've written. This means the copyright of Citar is shared by all its contributors. The situation is only different for projects with copyright assignment, e.g., FSF projects with copyright assignment or projects by companies with contributor license agreements (CLAs). I usually avoid contributing to projects with CLAs except Emacs projects. ;)

**Comment by bdarcus** [comment]
This commit should hopefully resolve this @aagon; let me know if not.

https://github.com/emacs-citar/citar/commit/ed7da18bfc057b1a3049f2bc0f984383cf08e0cd

**Comment by aagon** [comment]
This is perfect, thanks very much !

To answer your previous questions, for reference :

> Could you just omit those files from your package ?

We only remove files from the upstream source when we are forced to, for instance when we cannot be sure that they are DFSG-free (https://wiki.debian.org/DebianFreeSoftwareGuidelines).

We aren't to remove files solely on the basis of our not needing them.

> @bdarcus The files in @raxod502's directory are licensed under MIT. But given that I authored them, I am happy to relicense them under GPL-3+.

The issue was in fact merely a request for clarification, we didn't want to rely solely on our interpretation... MIT is among the DFSG-free licences, and is compatible with GPL-3+.

We'll edit our documentation accordingly.

Thank you again for your quick answer !

Best,

Aymeric

**Comment by minad** [comment]
> The issue was in fact merely a request for clarification, we didn't want to rely solely on our interpretation... MIT is among the DFSG-free licences, and is compatible with GPL-3+.

Of course. But having GPL3+ may simplify the license situation a bit? Thank you for creating all these Debian packages!

**Comment by raxod502** [comment]
It sounds like you all got this sorted, and in any case it was determined I wasn't the original copyright holder, but to the extent that the licensing status of any of my contributions to Selectrum are unclear, I have no objection whatsoever to their being included in other packages, or additionally released under the GPL.

**Comment by aagon** [comment]
> But having GPL3+ may simplify the license situation a bit?

I honestly have no idea.

> Thank you for creating all these Debian packages!

No problem. Feel free to mention them in the relevant READMEs, if you want.

**Comment by bdarcus** [comment]
Aside: is the package going to be called `elpa-citar`, even though it's not on elpa?

**Comment by minad** [comment]
melpa is also an elpa, isn't it?

**Comment by bdarcus** [comment]
IDK! If yes, that would explain it.

**Comment by aagon** [comment]
> Aside: is the package going to be called elpa-citar, even though it's not on elpa?

The source package is going to be called citar, the binary package elpa-citar. It is a common convention for all the packages maintained by our team.
