### ISSUE TITLE
Denote integration

### ISSUE THREAD

**Issue by pprevos** [emacs-citar/citar#713]
Hi Bruce,

I have the [citar-denote](https://github.com/pprevos/citar-denote/) package in a first alpha version. It enables me to link notes created with Denote to the bibliography.

Love your feedback on how it is written and perhaps some suggestions to streamline the caching function.

Regards

Peter

**Comment by bdarcus** [comment]
I'm no elisp expert, but I think you should remove this line, and users should set this themselves? 

https://github.com/pprevos/citar-denote/blob/185ab89244deda00770bd44c3fee20400091a9df/citar-denote.el#L122

> ... perhaps some suggestions to streamline the caching function.

Which is that?

**Comment by pprevos** [comment]
Hi, 

`(setq citar-notes-source 'citar-denote-source)` seems to be necessary otherwise citar does not cache the note files when first started and I have to do it manually. Is there are better way of achieving this

P:)

**Comment by bdarcus** [comment]
Are you saying that's true even if you add that line to your config?

**Comment by pprevos** [comment]
Looking at the `citar-org-roam` code, it does exactly the same, but wraps it in a function which is called through activating a minor mode. I am writing the new version of my code the same way.

**Comment by pprevos** [comment]
I just committed the new version which uses exactly the same approach as `citar-org-roam`. Seems to work OK. Now I an tinkering with some optimisation and then the deed is done.
