### ISSUE TITLE
inaccurate refresh/resync, readd manual refresh/resync

### ISSUE THREAD

**Issue by yuuyins** [emacs-citar/citar#716]
**Describe the bug**
citar doesn't accurately refresh/sync bib entries. outdated keys, or not including newly added ones. needs function for manually refreshing/resync. also using it with vertico is slow

sorry unappropriated report. no time.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Emacs version:**

**Additional context**

**Comment by bdarcus** [comment]
> ... still would be nice manual sync.

We did in the past, but removed it. 

https://github.com/emacs-citar/citar/pull/634/commits/ec6856d77fcdc95f2d159c485901e1623cf7c68b

I can't see any reason to add it back, and you're the first to mention it. So maybe explain a bit more in a separate issue, if you like?
