### ISSUE TITLE
Unable to add citations

### ISSUE THREAD

**Issue by pprevos** [emacs-citar/citar#719]
**Describe the bug**

**To Reproduce**
1. Minimal configuration (as in README)
2. Run `org-cite-insert`
3. Select entry and hit tab or enter
4. Message "Aborted"

**Expected behavior**
Citation(s) inserted

**Emacs version:**
- GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-31
- citar-20230101.1542

**Additional context**
The problem seems to be with the `citar-select-refs` (which I use in my package `citar-denote`). I can't seem to get it to return citation key(s).

**Comment by bdarcus** [comment]
I was able to confirm this. Sorry about that @pprevos.

@aikrahguzar -  I'm having some problems with my local emacs install, so not sure what I can contribute ATM. We may have to revert https://github.com/emacs-citar/citar/commit/37f6b6b1b82597f8dc17b58dbd21855d73074c31 for now, unless we get lucky and this is a simple fix.

**Comment by bdarcus** [comment]
Update, after getting Doom sorted, and testing a bit more.

The basic `org-cite-insert` no longer works, except for this scenario:

- add more than one key, and hit enter

**Comment by pprevos** [comment]
I tested the updated package and everything works as before. Thanks for the reversal.

**Comment by aikrahguzar** [comment]
> I decided to revert [37f6b6b](https://github.com/emacs-citar/citar/commit/37f6b6b1b82597f8dc17b58dbd21855d73074c31) for now, as I don't have the time, or knowledge of this particular code, to figure out what's going on. I think if you can manage to fix it, @aikrahguzar, you can just open another pull request with the same branch.

That is the best course of action for now. I will look at it in a few days and try to fix this.
