### ISSUE TITLE
org-ref and citar/org-cite compatibility and features

### ISSUE THREAD

**Issue by deb75** [emacs-citar/citar#724]
Hi,

I would like to jump from `org-ref` to `citar/org-cite`.

I am just wondering if the citations in my org files, which are based on `org-ref` : [[cite:&citationkey]]
will always be valid with `citar/org-cite` ?

Furthermore, here is how I configure `org-ref` for a particular org file
```
#+LATEX_HEADER: \usepackage[citestyle=authoryear-icomp,bibstyle=authoryear, hyperref=true,backref=true,maxcitenames=3,url=false,backend=biber,natbib=true]{biblatex}
#+LATEX_HEADER: \addbibresource{d:/edebry/Documents/reference/bibliography.bib}
```
Do I need to change this for `citar/org-cite` ?

Also, a nice feature of `org-ref` I appreciate is the handling of references, especially that of math
environnments. Does `citar/org-ref` manages these references ?

Regards

**Comment by bdarcus** [comment]
> I would like to jump from `org-ref` to `citar/org-cite`.

Cool!

> I am just wondering if the citations in my org files, which are based on `org-ref` : [[cite:&citationkey]] will always be valid with `citar/org-cite` ?

You may want to read through this page to get a general sense of the place of this package.

https://github.com/emacs-citar/citar/wiki/Comparisons#citar-in-context

On your question, citar  defers to org itself for what is and isn't a citation (org does the parsing etc). From that POV, it isn't.

But you can also configure custom major mode functions:

https://github.com/emacs-citar/citar/wiki/major-mode-functions
 
> Furthermore, here is how I configure `org-ref` for a particular org file
> 
> ```
> #+LATEX_HEADER: \usepackage[citestyle=authoryear-icomp,bibstyle=authoryear, hyperref=true,backref=true,maxcitenames=3,url=false,backend=biber,natbib=true]{biblatex}
> #+LATEX_HEADER: \addbibresource{d:/edebry/Documents/reference/bibliography.bib}
> ```
> 
> Do I need to change this for `citar/org-cite` ?

I don't have time to look into the details on this ATM, but maybe check the org manual? There's also a few good blog posts on `org-cite` that should explain this. It's easy.

It does sound like you want to use the `oc-biblatex` export processor, however (if you're using biblatex).

> Also, a nice feature of `org-ref` I appreciate is the handling of references, especially that of math environnments. Does `citar/org-ref` manages these references ?

You mean cross-references?

No; I consider that out of scope; see #427.

PS - I may convert this to a discussion.
