### ISSUE TITLE
Citar capf not working

### ISSUE THREAD

**Issue by deb75** [emacs-citar/citar#727]
**Describe the bug**

Citar completion at point is not working.

**To Reproduce**
1. Open an org file
2. Type "cite:@"
3. M-x completion-at-point
4. Nothing happens

**Expected behavior**

Should open a menu with possible completions

**Emacs version:**

windows 11 / mingw64 / emacs 30.0.60

**Additional context**

I have `citar`, `org-cite` configured and working as expected as for inserting citations.
When loading the emacs init file, I noticed the error : 
```
run-hooks: Autoloading file c:/Users/xxxx/.emacs.d/elpa/citar-20230129.1922/citar-capf.elc failed to define function citar-capf-mode
```
This error can be reproduced by `M-x citar-capdf-mode`
The citar configuration is :  
```elisp
(use-package citar
  :custom
  (citar-library-paths ... )
  (org-cite-global-bibliography ... )
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-bibliography org-cite-global-bibliography)
  :config
  (add-to-list 'citar-file-open-functions (cons "pdf" #'org-pdftools-open))
  (setq citar-library-file-extensions (list "pdf" "jpg")
        citar-file-additional-files-separator "-"
        citar-notes-paths ... )
  :hook ((org-mode markdown-mode tex-mode latex-mode reftex-mode) . citar-capf-mode)
  :bind
  (:map org-mode-map :package org ("C-c b" . #'org-cite-insert)))

```

**Comment by bdarcus** [comment]
Well, the error is because there's no longer any `citar-capf-mode`.

Did you have it working earlier?

That code in general needs work (see #660), which is largely why it's not currently documented. 

And I don't use it, so am actually not sure what the right configuration should be.

Perhaps you can figure out how to modify the config so you remove the error, and get it to load correctly, and see if you still have the same issue?

**Comment by bdarcus** [comment]
You can see what the mode did [here](https://github.com/mclear-tools/citar-capf/blob/5677db97ea6252b797c1b3c7cfcb9f3be005b05d/citar-capf.el#L103) , as a basis for the config?

**Comment by mclearc** [comment]
> @mclearc - are you using `citar-capf` these days? Any tips?

hi @bdarcus -- I'm actually just using [a very basic capf](https://github.com/mclear-tools/bibtex-capf) I wrote that just uses parsebib. At least in my use case I've found this is more reliable and responsive (as per [this comment](https://github.com/emacs-citar/citar/issues/660#issuecomment-1419377554)) than using citar (though I do still use citar -- just more for note-related stuff).

**Comment by bdarcus** [comment]
> hi @bdarcus -- I'm actually just using [a very basic capf](https://github.com/mclear-tools/bibtex-capf) I wrote that just uses parsebib. At least in my use case I've found this is more reliable and responsive (as per [this comment](https://github.com/emacs-citar/citar/issues/660#issuecomment-1419377554)) than using citar (though I do still use citar -- just more for note-related stuff).

Have you changed anything in the activation code that would explain what the OP is seeing, that we might apply here?

The candidates/caching is a separate issue that I'm more comfortable with; I actually have an idea on that.

**Comment by bdarcus** [comment]
> EDIT: reading the `bibtex-capf` function, it does seem the same. Maybe a config issue?

I see the issue here.

I had used this to config, from IELM:

```elisp
(add-hook 'completion-at-point-functions #'citar-capf -90 t)
```

That last argument makes the hook local, and so to IELM, which means it doesn't work in org-mode.

@deb75 - can you try this? It should work:

```elisp
(add-hook 'completion-at-point-functions #'citar-capf -90)
```

@mclearc - as I suggested, I don't really understand capf config. Any suggestions on what we put in the README for this?

**Comment by bdarcus** [comment]
> Note though that for the list addition to work it has to be added in every mode, which is why I use hooks.

Oops; just pushed the earlier iteration.

How would I change it to use hooks, without adding a minor-mode?

**Comment by mclearc** [comment]
> How would I change it to use hooks, without adding a minor-mode? 

I assume by adding one for each mode:

```emacs-lisp
(add-hook 'org-mode-hook (lambda () (add-hook 'completion-at-point-functions #'citar-capf -90)))
```
etc...

**Comment by bdarcus** [comment]
@mclearc how do you find the UX with the simple complete-on-the-citekey?

I can see it may have some appeal in that context?

**Comment by bdarcus** [comment]
That worked!

I was more worried about the padding between the candidate and the annotation, but that turned to be a non-issue.

**Comment by bdarcus** [comment]
Any luck with this @deb75?

**Comment by deb75** [comment]
👍 👍 👍 

Regards

**Comment by deb75** [comment]
Actually, it suddenly stops working, answering "No match" although
I use the same word which was working before.

In the message buffer, I get some errors : 
```
Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file. [4 times]
Error in post-command-hook (cursor-sensor--detect): (wrong-type-argument integer-or-marker-p nil)
redisplay--pre-redisplay-functions: (wrong-type-argument integer-or-marker-p nil)
Beginning of buffer
```

but I am not sure if they are all related to `citar-capf`.

**Comment by bdarcus** [comment]
Oddly enough, I also can't get it to work now, though I get no error.

Your error, however, does look like it's related to `cursor-sensor`.
