### ISSUE TITLE
Indicator spacing wrong with icons

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#759]
_converting from a discussion_

----------------------------

After updating, and replacing my citar config with the example out of the wiki, I noticed that citar does look different. For example, the spacing between the icons is gone. How do I get it back?

Thank you!

<img width="77" alt="Bildschirm­foto 2023-03-22 um 20 07 40" src="https://user-images.githubusercontent.com/39911339/227012121-c511c65e-1b0b-4ebe-ae36-c76ed0d57715.png">

_Originally posted by @gwbrck in https://github.com/emacs-citar/citar/discussions/754#discussioncomment-5397164_

**Comment by bdarcus** [comment]
[This](https://github.com/emacs-citar/citar/commit/dcd8c3f0dd4bb5ca75082eb2005e9604a4957c37#diff-edf00f713d343a2437767c9ff28665dda570370c7c5e02e76127171b7d685bddL1239-L1259) is the previous code that I adapted.

There's something subtle I'm not yet seeing that seems to incorrectly calculate the alignments here.

I checked, for example, and `string-width` returns `1` on the icons, so don't think that's the problem.

**Comment by robmoss** [comment]
I'm also experiencing this issue (I didn't realise there were meant to be spaces between the icons) and `(string-width (citar--make-indicator-symbols "abc has:files has:links has:notes"))` evaluates to 6 — is that correct, or too narrow? I've tried `(setq citar-symbol-separator " a ")`, which suggests it's too narrow. 

I have no idea how to fix this. The following hack inserts a space between each pair of tags, but isn't a good solution: `:align-to (+ 1 (string-width str))`

**Comment by bdarcus** [comment]
> The following hack inserts a space between each pair of tags, but isn't a good solution: `:align-to (+ 1 (string-width str))`

What I had in mind is adding a property to the indicator spec, so one could do this:

```elisp
     :symbolwidth 2
```

Make sense?

I think that's the right place to put it; I was just struggling how to integrate that integer into the output, but your comment points me in the right direction, so thank you!

**Comment by bdarcus** [comment]
I can't test it ATM, but I've opened a PR with a fix that _should_ work in #762,

**Comment by gwbrck** [comment]
I tried #762 and can confirm, the following shows the spacing correct:

```elisp
(setq citar-indicator-notes-icons
    (citar-indicator-create
     :symbol (all-the-icons-material
              "speaker_notes"
              :face 'all-the-icons-blue
              :v-adjust -0.3)
     :function #'citar-has-notes
     :symbolwidth 2
     :tag "has:notes"))
```
For me, `:symbolwidth`without a separator symbol other than space is fine. So, for me, no need for `:emptysymbol`. But I understand, some people want a pipe or something between icons.

**Comment by bdarcus** [comment]
Thanks for confirming; I'll merge it!

> So, for me, no need for `:emptysymbol`. But I understand, some people want a pipe or something between icons.

The primary use case for this was something I was playing with very early on, where that property could be an icon of a dark color.

So rather than a space representing empty, it would be a dim icon.

That's the idea; maybe a bit overkill, but with a default, maybe worth keeping?

**Comment by gwbrck** [comment]
Ah! I misunderstood `:emptysymbol`. It's a placeholder for when there is no file, note or link. I like that!

**Comment by bdarcus** [comment]
Would it be more clear to change symbolwidth to just padding?

**Comment by gwbrck** [comment]
Nice! Thank you! :)
