### ISSUE TITLE
when selecting multiple references, keep the current filter

### ISSUE THREAD

**Issue by JonatanSahar** [emacs-citar/citar#783]
when selecting multiple references using `citar-open`, once I hit `TAB` to select a ref, the filtering I had applied is cancelled. The most common scenario for me it to look for a specific tag, wanting to select several refs which are tagged with it - currently I need to search for the tag again for each ref.

**Comment by bdarcus** [comment]
Sorry for the delay; realize I forgot to reply to it!

I would definitely like to figure this out, though am unsure on how.

Note: there's another issue here related to this that I'll link to, once I find it.

**Comment by bdarcus** [comment]
Closing since a duplicate, and I reopened #714.
