### ISSUE TITLE
Only citation key being used for narrowing results

### ISSUE THREAD

**Issue by rdiaz02** [emacs-citar/citar#791]
Dear All,

I must be doing something rather silly, but after more than one hour of looking around I can't see what I am doing wrong. 

This is the simple config I am using (loaded after `emacs -Q`):

```
(require 'package)
(package-initialize)

(use-package vertico
  :init
  (vertico-mode)
  )

(use-package citar
  :custom
  (citar-bibliography '("/home/ramon/tmp/example.bib"))
  )
```

If I use, say, `citar-insert-citation` , as soon as I start typing in the minibuffer, the search is narrowed using ONLY the citation key.  For example,  in the following case
![cit1](https://github.com/emacs-citar/citar/assets/1688611/46e6a0b9-7fde-4917-8105-1383cd4c7a28)

typing "models" (or "Models") does not select the first entry; actually, typing "m" leaves no entries, since none of the references has a key with the letter "m".
![cit2](https://github.com/emacs-citar/citar/assets/1688611/b657c14c-ec28-4661-9525-b32f677a3e6b)

Likewise, as soon as I type "U" I end with 0 entries (even when a lastname has that letter; no keys have "U").

I do not think this is intended behavior, and I think I should be able to narrow with terms from the authors, title, and other fields ("By default, citar filters parsed data based on the fields specified in ‘citar-templates’, ‘citar-file-variable’ ‘citar-crossref-variable’, and ‘citar-link-fields’." as from the docstring for `citar-additional-fields`). In fact, the example in https://github.com/emacs-citar/citar/issues/252#issuecomment-904497183 shows selecting an entry because of a "hidden author named (...)".

So I must surely be doing something wrong. But I just can figure out what.

**Comment by bdarcus** [comment]
> I do not think this is intended behavior, and I think I should be able to narrow with terms from the authors, title, and other fields ...

Correct.

At first thought, I have no ideas. If you see it, you should be able to narrow on it. I don't see how it's possible that you can't.

**Comment by roshanshariff** [comment]
I'm not sure either, but this might have something to do with your completion styles? The citation key is (invisibly) at the beginning of each candidate string, so if your completion string isn't matching in the middle of the string, you'd see that behaviour. Something like [orderless](https://github.com/oantolin/orderless) should work correctly.

**Comment by bdarcus** [comment]
Oh yes; that makes sense.

Definitely try orderless..

**Comment by rdiaz02** [comment]
Yes, that was it, thank you!!  Adding
```
(use-package orderless
  :after citar
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion))))
  )
  
```
(taken from the README of orderless) has everything working.


I rarely use the vertico/embark/orderless/marginalia system. I wonder if saying explicitly, in the README, that orderless is necessary for matching on authors, titles, etc, would prevent mistakes similar to mine. I can open a PR.

**Comment by bdarcus** [comment]
> I can open a PR.

Yes please.

The only caveat is it's not only orderless. It just has to be a completion style similarly order independent.

I do think we recommend orderless already though?

**Comment by rdiaz02** [comment]
> > I can open a PR.
> 
> Yes please.
> 

Done

> The only caveat is it's not only orderless. It just has to be a completion style similarly order independent.
> 

I've tried to say exactly that.

> I do think we recommend orderless already though?
> 
> Edit: yes, we already do "strongly recommend" it. But you can add a note on why.


Yes, indeed. But for someone unfamiliar with orderless et al., it might not be obvious what are the consequences of not using orderless (I am an example of that).
