### ISSUE TITLE
The Homepage button on melpa leads to a 404

### ISSUE THREAD

**Issue by doolio** [emacs-citar/citar#813]
[Melpa](https://melpa.org/#/citar-embark).

**Comment by bdarcus** [comment]
Hmm ... do you know how to fix that?

It seems that the MELPA build scripts are automatically creating the URL somehow, so am not sure how to override it.

**Comment by doolio** [comment]
I don't I'm afraid (@purcell might) and it is the same on [MELPA Stable](https://stable.melpa.org/#/citar-embark) too. The Source Code button works though. The recipe looks ok to me.

**Comment by purcell** [comment]
Turns out it's wrong [in the source code here](https://github.com/emacs-citar/citar/blob/e21bf22b29d8ca40649517bb7dc503765f240282/citar-embark.el#L13C57-L13C57), which is where we get it from. 😁

**Comment by bdarcus** [comment]
Oh no; sorry for the noise!

**Comment by purcell** [comment]
#teamwork 💪
