### ISSUE TITLE
Problems rendering superscripts correctly for in-text citations when exporting to ODT

### ISSUE THREAD

**Issue by matogoro** [emacs-citar/citar#829]
**Describe the bug**
Hi,

I'm having trouble getting `citar` and `citeproc-el` to render certain superscripted citations properly when exporting to ODT (using `org-cite`).  Basically, the generated ODT document shows the underlying `org` shorthand (`^{1}`) rather than a proper superscripted citation.  

Unsurprisingly, only CSL styles that rely on superscript citations (e.g., `nature.csl`, `american-medical-association.csl`, etc.) are affected.  This is not an issue with certain CSL styles that don't require superscript numbers  (e.g., `springer-vancouver.csl`).

Some things I've noticed:

- regardless of how in-text citations are displayed, bibliographies render correctly according to the style file
- exporting to HTML displays the superscripts properly—it's only ODT that has issues
- standard superscripted text (i.e., where I just type the shorthand in `org-mode`) renders correctly in the ODT file—only the superscripted citations don't get converted
- I've been able to export to superscripted references to ODT successfully before using `org-ref`, so this makes me believe that something is not being piped to the `ox-odt` exporter appropriately

**To Reproduce**
A (stripped down) version of my configuration is below:

```
(use-package citeproc)

(use-package citar
  :custom
  (org-cite-global-bibliography '("~/Multimedia/Literature/SciLi/index.bib"))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-bibliography org-cite-global-bibliography)
  (citar-citeproc-csl-styles-dir "~/Documents/Zettelkasten/Templates/Text/CSL/styles")
  (citar-citeproc-csl-locales-dir "~/Documents/Zettelkasten/Templates/Text/CSL/locales")  ; cloned official CSL locales repository
  (citar-format-reference-function #'citar-citeproc-format-reference)
  :hook
  (LaTeX-mode . citar-capf-setup)
  (org-mode . citar-capf-setup))
```

In the manuscript buffer, I execute `citar-citeproc-select-csl-style` and select the appropriate CSL file (e.g., Nature).  I also put in the following header to ensure the proper CSL file is loaded:

`#+CITE_EXPORT: csl ~/Documents/Homework/Zettelkasten/Templates/Text/CSL/american-medical-association.csl`

I export using `org-export-dispatch` to ODT, and the in-text citations of the resultant ODT file are displayed as `^{1}` when viewed in LibreOffice.

**Expected behavior**
Correct rendering of superscript citations in exported ODT files.  Any help would be greatly appreciated!

**Emacs version:**
GNU Emacs 29.3
Org 9.7-pre

**Comment by bdarcus** [comment]
Citar has no role in citation/bibliography formatting, so this has to be something citeproc-el related.

cc @andras-simonyi

**Comment by matogoro** [comment]
Ah, my mistake.  I've moved this question over to `citeproc-el`.  Although is you have any insight here, I would be grateful.  Thanks!

**Comment by bdarcus** [comment]
Per my edit, it's also possibly org-related, but @andras-simonyi would likely know.
