### ISSUE TITLE
`(wrong-type-argument hash-table-p t)` while evaluating `(citar-select-ref)` 

### ISSUE THREAD

**Issue by WeissP** [emacs-citar/citar#846]
**Describe the bug**

Got following error when I tried to call `(citar-select-ref)`.

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p t)
  gethash("{Reif, Maximilian and Neumann, Thomas}" t)
  #f(compiled-function (str) #<bytecode 0x1aeb68f70b974a23>)("{Reif, Maximilian and Neumann, Thomas}")
  parsebib--expand-strings(("{Reif, Maximilian and Neumann, Thomas}") t)
  parsebib--parse-bib-value(515 t t)
  parsebib--parse-bibtex-field(515 #<hash-table equal 0/65 0xb2c708f> nil t)
  parsebib-read-entry("Article" nil #<hash-table equal 0/65 0xb2c708f> nil t)
  parsebib-parse-bib-buffer(:entries #<hash-table equal 0/65 0xb2e350d> :strings #<hash-table equal 0/65 0xb2c708f> :expand-strings t :inheritance t :fields nil :replace-TeX t)
  #f(compiled-function (file) #<bytecode -0x64ecb7e896825c0>)("/home/weiss/Downloads/x.bib")
  parsebib-parse("/home/weiss/Downloads/x.bib" :entries #<hash-table equal 0/65 0xb2e350d>)
  citar-cache--update-bibliography(#s(citar-cache--bibliography :filename "/home/weiss/Downloads/x.bib" :buffers nil :props nil :entries #<hash-table equal 0/65 0xb2e350d> :format-string #("${author editor:30%sn}     ${date year issued:4}  ..." 0 64 (face citar-highlight) 64 135 (face citar)) :preformatted #<hash-table equal 0/65 0xb2e373b>) (:size 516 :mtime (26394 2833 195487 619000) :hash "dc9d3c0135bec8f51ca8ace3c09c26be30df046a" :fields ("author" "editor" "date" "year" "issued" "title" "=key=" "id" "=type=" "tags" "keywords" "journal" "journaltitle" "publisher" "container-title" "collection-title" "file" "crossref" "doi" "pmid" "pmcid" "url")))
  citar-cache--get-bibliography("/home/weiss/Downloads/x.bib")
  #f(compiled-function (filename) #<bytecode 0x118d505f16154f75>)("/home/weiss/Downloads/x.bib")
  citar-cache--get-bibliographies(("/home/weiss/Downloads/x.bib") global)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_31>(global)
  citar--bibliographies()
  citar--format-candidates()
  citar-select-refs(:multiple nil :filter nil)
  citar-select-ref()
  eval-buffer()  ; Reading at buffer position 95
  funcall-interactively(eval-buffer)
  command-execute(eval-buffer record)
  execute-extended-command(nil "eval-buffer" "eval-buffere")
  funcall-interactively(execute-extended-command nil "eval-buffer" "eval-buffere")
  command-execute(execute-extended-command)
```

**To Reproduce:**
1. Open Emacs in a basic mode by running `emacs -q`.
2. Evaluate the following code in the buffer:
```
(require 'citar)
(setq citar-bibliography '("/home/weiss/Downloads/x.bib"))
(citar-select-ref)
```

Here’s the content of `x.bib`:

```
@Article{Reif2022,
  author       = {Reif, Maximilian and Neumann, Thomas},
  title        = {A scalable and generic approach to range joins},
  journal      = {Proceedings of the VLDB Endowment},
  year         = 2022,
  volume       = 15,
  number       = 11,
  month        = jul,
  pages        = {3018–3030},
  issn         = {2150-8097},
  doi          = {10.14778/3551793.3551849},
  url          = {http://dx.doi.org/10.14778/3551793.3551849},
  publisher    = {Association for Computing Machinery (ACM)}
}
```

**Emacs version:**

29.4

**Comment by dschrempf** [comment]
I also get this error.

**Comment by dschrempf** [comment]
It does not happen when the bibliography is empty, but always happens when there is at least one entry (I tried different ones).

I also tried without any (citar-specific) custom configuration. My back trace looks pretty much the same as WeissPs, but I can provide it if need be.

**Comment by dschrempf** [comment]
A minimal bib file triggering the error is
```
@article{a,
  author          = {b},
}
```

**Comment by bdarcus** [comment]
You mean this error? `(wrong-type-argument hash-table-p t)`?

If I run the test script in the repo (`/test/manual/run.sh`), that should mean I'm running the code in main; right? And based on what you two report, it seems it should generate the error also?

Because it doesn't.

**Comment by WeissP** [comment]
I have tried evaluating `(citar-select-ref)` after I run `/test/manual/run.sh`, but the same error still occurs. Does it mean that the issue originates from the Emacs version rather than the versions of `citar` and its dependencies?

**Comment by bdarcus** [comment]
> I have tried evaluating `(citar-select-ref)` after I run `/test/manual/run.sh`, but the same error still occurs. Does it mean that the issue originates from the Emacs version rather than the versions of `citar` and its dependencies?

Hmm ... what platform are you guys on?

I'm on Linux, but the same general version number: 29.4.

**Comment by heraplem** [comment]
I am also getting this error on both macOS and Linux, Emacs version >= 30.0.91.

**Comment by WeissP** [comment]
> After I run /test/manual/run.sh, the same error still occurs.

Ignore this. I can't reproduce it anymore; sorry.

After a long, boring experiment, I found the issue is related to `org-ref` in a really strange way. That is, if I have `org-ref` installed and the following code is loaded before `org`: 

```
(with-eval-after-load 'org
  (require 'org-ref)
  )
```

Then the error occurs. Strangely enough, if instead I just evaluate `(require 'org-ref)`, everything is fine.

I don't expect anyone to be able to reproduce the issue in this way (since it may also relate to my other config potentially), but for someone who also meets this issue, you might want to check if  `org-ref` is installed as well.

**Comment by heraplem** [comment]
I don't have `org-ref` installed, so that's not a necessary condition.

**Comment by heraplem** [comment]
Oh, I think I know where this is coming from. In my case, this is due to an error in `parsebib`, specifically in `parsebib-postprocessing-excluded-fields`. It was introduced in joostkremers/parsebib@3e2f46f and fixed in either joostkremers/parsebib@dea57d1 or joostkremers/parsebib@30c989d.

Unfortunately, I'm using [emacs-overlay](nix-community/emacs-overlay), and [MELPA updates have been broken for a while now](https://github.com/nix-community/emacs-overlay/issues/444).

**Comment by heraplem** [comment]
Sorry for the spam. If anyone else is using emacs-overlay, the last commit before the breakage appears to be nix-community/emacs-overlay@87e8ffccb53aa67dfaab7bd4fd9f27b543e73cec.

**Comment by dschrempf** [comment]
Thanks for analyzing this @heraplem! For reference, the upstream issues are https://github.com/nix-community/emacs-overlay/issues/444 and https://github.com/NixOS/nixpkgs/issues/349791.

IMO, this issue should be closed.

**Comment by WeissP** [comment]
I am actually also using Nix to manage Emacs packages. Therefore, what @heraplem analyzed should apply to my case as well.
