### ISSUE TITLE
Error during parsing bib file

### ISSUE THREAD

**Issue by drcxd** [emacs-citar/citar#851]
**Describe the bug**
It seems that when I open an org-mode file that contains a citation, citar would try to update the bibliography. However, the parsing during the update failed and something went wrong.

Here is the error message from the `*Message*` buffer:

```
Updating bibliography ~/org-roam/references.bib...
Error during redisplay: (jit-lock-function 1) signaled (parsebib-error "Expected one of (comment), got `C' at position 979,1")
```

**To Reproduce**

To reproduce, use the following config file:

``` emacs-lisp
;; =staraight.el=


(setq straight-use-package-by-default t)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'org) ;; to fix org version mismatching

;; citar


(use-package citar
  :init
  (setq org-cite-global-bibliography '("~/org-roam/references.bib") ;; set to your bibliography
        org-cite-insert-processor 'citar
        org-cite-follow-processor 'citar
        org-cite-activate-processor 'citar
        citar-bibliography org-cite-global-bibliography
        org-cite-export-processors '((t . (csl "modern-language-association.csl"))))
  :hook
  (org-mode . citar-capf-setup))

(use-package citar-embark
  ;; :defer t
  :after (citar embark)
  ;; :no-require
  :diminish citar-embark-mode
  :config (citar-embark-mode))

;; You can get the csl style files from
;; https://github.com/citation-style-language/styles

;; (setq org-cite-csl-styles-dir "path/to/styles/dir")

```

After Emacs launchs, open an org file that contains a citation link should reproduce the error. Note that the bibliography file should contain at least one comment line, such as:
```
@Comment asdfasdf
```
Note the capitalized `C`.

**Expected behavior**
There should be no such error.

**Screenshots**
No screenshots.

**Emacs version:**
GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05

**Additional context**
I am using Emacs on Windows.

Some comments about this issue.

I thought the problem comes from the parsebib package, since the log says that it raised the error. Thus, I tested the function `parsebib--@comment` by invoking it separately in the `*scratch*` buffer. In such situation, the function can correctly parse `@Comment` and `@comment`. However, either change the `@Comment` to `@comment` in the bibliography, or change the keyword used by `parsebib--@comment` to `"Comment"` can fix the issue.

Then I tested `citar--bibliographies`, which should be the driver code that invoked `parsebib--@comment`. This function, when evaluated using `eval-expression` can also correctly parse the biblography.

Thus, the issue can only occur when the parsing is initiated by opening an org-mode file that contains a citation link. 

I have no idea why this would happen. I have tried to setup breakpoint on `paresebib--@comment` by `C-u C-M-x` it, but the debugger is not trigerred when I open the said org-mode file.

Is this related to #849 ?

**Comment by bdarcus** [comment]
Strange.

@joostkremers - any ideas?

**Comment by joostkremers** [comment]
Sounds like an issue with `case-fold-search` being set to `nil` somewhere. The default value of this variable is `t`, meaning that searching for `"comment"` also finds `"Comment"`. I suspect not many people actually change this default, so parsebib mostly just works. But if a user or a package sets it to `nil` for some reason, I'd expect parsebib to error out with exactly this kind of error. I should probably wrap the higher-level API functions in a `(let ((case-fold-search t))...` just in case.

Without a sample (minimal) `.org` and `.bib` file to test with, though, I can't be sure.

**Comment by drcxd** [comment]
@joostkremers Wrapping the higher-level API functions may be a good idea. I can confirm that `find-file` somehow set `case-fold-search` to `nil` using `debug-on-variable-change`:

```
Debugger entered--setting case-fold-search to nil: 
  debug--implement-debug-watch(case-fold-search nil set nil)
  abbreviate-file-name("~/")
  read-file-name-default("Find file: " nil "~/" confirm-after-completion nil nil)
  read-file-name("Find file: " nil "~/" confirm-after-completion)
  find-file-read-args("Find file: " confirm-after-completion)
  byte-code("\300\301\302 \"\207" [find-file-read-args "Find file: " confirm-nonexistent-file-or-buffer] 3)
  command-execute(find-file)
```

**Comment by joostkremers** [comment]
> @joostkremers Wrapping the higher-level API functions may be a good idea. 

On second thought, I think `let`-binding `case-fold-search` in `parsebib--keyword` would be the better way to go. It's a less sweeping change, less of a risk that other issues get swept under the rug...

> I can confirm that `find-file` somehow set `case-fold-search` to `nil` using `debug-on-variable-change`:

[...]

It seems the actual change takes place in `abbreviate-file-name`, but...

> Though this may not be the case that make `parsebib--@comment` fail on `@Common`, there just may be chances that other code interfere with this variable.

... I tend to agree with this: It's unlikely that this particular case is the cause of the issue.

**Comment by joostkremers** [comment]
> On second thought, I think `let`-binding `case-fold-search` in `parsebib--keyword` would be the better way to go. It's a less sweeping change, less of a risk that other issues get swept under the rug...

I just pushed a commit that does this. Could you please test it?

**Comment by drcxd** [comment]
> On second thought, I think `let`-binding `case-fold-search` in `parsebib--keyword` would be the better way to go. It's a less sweeping change, less of a risk that other issues get swept under the rug...

Agreed. I just test the latest change and it fixes the issue. Thanks!
